POST = {
 "date": "2026-10-31", "accent": "green", "cover_word": "German", "cover_sub": "Classic names & what they mean",
 "title": "60 German Baby Names: Strong Classics and Modern Favorites with Meanings",
 "description": "German baby names for boys and girls with meanings and pronunciation, from classics like Otto, Matilda, and Conrad to the names German parents choose today.",
 "tags": ["german baby names", "german boy names", "german girl names", "germanic names", "european baby names", "baby names"],
 "intro": [
  "A surprising number of the most traditional English names are German in origin. William, Henry, Charles, Robert, Richard, Emma, and Alice all came into English from Germanic languages, most of them with the Normans in 1066.",
  "Old Germanic names were built like compound words: two elements joined together, each with a meaning. *Wil* (will) plus *helm* (helmet, protection) gives Wilhelm, or William. Once you know a handful of these elements, you can read the meaning of dozens of names. This list has 60, with the meaning of each and the German pronunciation where it differs from English.",
 ],
 "takeaway": "Most classic German names are two-part compounds, and the same building blocks repeat: *bert* means bright, *rich* means ruler, *hard* means brave or hardy, *wolf* means wolf, and *fried* means peace. That is why German names so often mean things like \"bright fame\" (Robert) or \"peaceful ruler\" (Frederick). For names from the neighboring north, see our [Scandinavian baby names](/blog/scandinavian-baby-names/).",
 "sections": [
  {"h": "How to Read a German Name",
   "before": [
    "These are the elements you will see again and again in the tables below:",
    "| Element | Meaning | Found in |\n|---------|---------|----------|\n| adal / adel | noble | Adelaide, Albert, Alice |\n| bert / brecht | bright | Robert, Albert, Bertha |\n| rich / ric | ruler, power | Richard, Henry, Frederick |\n| hard / hart | brave, hardy | Bernard, Leonard, Gerhard |\n| fried / frid | peace | Frederick, Siegfried, Frieda |\n| wolf / ulf | wolf | Wolfgang, Rudolph, Rolf |\n| hild | battle | Matilda, Hilda |\n| ger | spear | Gerard, Gertrude |\n| wil | will, desire | William, Wilhelmina |\n| sieg | victory | Siegfried, Sigmund |",
   ]},
  {"h": "German Girl Names",
   "rows": [
    ["Emma", "Girl", "Germanic", "\"Whole, universal\"", "EM-uh"],
    ["Ada", "Girl", "Germanic", "\"Noble\"", "AY-duh"],
    ["Adelaide", "Girl", "Germanic", "\"Noble kind\"; German Adelheid", "AD-uh-layd"],
    ["Heidi", "Girl", "German", "Pet form of Adelheid", "HY-dee"],
    ["Matilda", "Girl", "Germanic", "\"Mighty in battle\"", "muh-TIL-duh"],
    ["Frieda", "Girl", "German", "\"Peace\"", "FREE-duh"],
    ["Ida", "Girl", "Germanic", "\"Work, labor\"", "EYE-duh"],
    ["Amelia", "Girl", "Germanic", "From *amal*, \"work\"", "uh-MEEL-yuh"],
    ["Irma", "Girl", "Germanic", "\"Whole, universal\"", "UR-muh"],
    ["Wilhelmina", "Girl", "German", "Feminine form of Wilhelm, \"resolute protector\"", "wil-hel-MEE-nuh"],
    ["Mina", "Girl", "German", "Short form of Wilhelmina", "MEE-nuh"],
    ["Gisela", "Girl", "Germanic", "\"Pledge\"", "GEE-zeh-lah"],
    ["Hilda", "Girl", "Germanic", "\"Battle\"", "HIL-duh"],
    ["Bertha", "Girl", "Germanic", "\"Bright\"", "BUR-thuh"],
    ["Ottilie", "Girl", "German", "\"Wealth, fortune\"", "oh-TEE-lee-eh"],
    ["Greta", "Girl", "German", "Short form of Margarete, \"pearl\"", "GRAY-tah"],
    ["Gretchen", "Girl", "German", "Pet form of Margarete", "GRETCH-en"],
    ["Liesel", "Girl", "German", "Pet form of Elisabeth", "LEE-zel"],
    ["Lotte", "Girl", "German", "Short form of Charlotte", "LOT-teh"],
    ["Anneliese", "Girl", "German", "A blend of Anna and Liese", "AH-neh-lee-zeh"],
    ["Marlene", "Girl", "German", "A blend of Maria and Magdalene", "mar-LAY-neh"],
    ["Romy", "Girl", "German", "Pet form of Rosemarie", "RO-mee"],
    ["Leni", "Girl", "German", "Pet form of Helene or Magdalena", "LAY-nee"],
    ["Carla", "Girl", "German", "Feminine form of Karl, \"free man\"", "KAR-lah"],
    ["Elke", "Girl", "Frisian / German", "Pet form of Adelheid", "EL-keh"],
    ["Lorelei", "Girl", "German", "The name of a rock on the Rhine, probably \"murmuring rock\"", "LOR-uh-lye"],
    ["Hedwig", "Girl", "Germanic", "\"Battle, combat\"", "HED-vikh"],
   ]},
  {"h": "German Boy Names",
   "rows": [
    ["Otto", "Boy", "Germanic", "\"Wealth, fortune\"", "OT-oh"],
    ["Hugo", "Boy", "Germanic", "\"Mind, spirit\"", "HYOO-go"],
    ["Conrad", "Boy", "Germanic", "\"Bold counsel\"", "KON-rad"],
    ["Kurt", "Boy", "German", "Short form of Konrad", "KURT"],
    ["Leopold", "Boy", "Germanic", "\"Bold people\"", "LEE-uh-pold"],
    ["Frederick", "Boy", "Germanic", "\"Peaceful ruler\"; German Friedrich", "FRED-rik"],
    ["Fritz", "Boy", "German", "Pet form of Friedrich", "FRITS"],
    ["Henry", "Boy", "Germanic", "\"Home ruler\"; German Heinrich", "HEN-ree"],
    ["William", "Boy", "Germanic", "\"Resolute protector\"; German Wilhelm", "WIL-yum"],
    ["Charles", "Boy", "Germanic", "\"Free man\"; German Karl", "CHARLZ"],
    ["Albert", "Boy", "Germanic", "\"Noble and bright\"", "AL-burt"],
    ["Robert", "Boy", "Germanic", "\"Bright fame\"", "ROB-urt"],
    ["Richard", "Boy", "Germanic", "\"Brave ruler\"", "RICH-urd"],
    ["Bernard", "Boy", "Germanic", "\"Brave as a bear\"", "bur-NARD"],
    ["Leonard", "Boy", "Germanic", "\"Brave as a lion\"", "LEN-urd"],
    ["Gerard", "Boy", "Germanic", "\"Brave with the spear\"; German Gerhard", "juh-RARD"],
    ["Walter", "Boy", "Germanic", "\"Ruler of the army\"", "WAWL-tur"],
    ["Ludwig", "Boy", "German", "\"Famous in battle\"; the German form of Louis", "LOOT-vikh"],
    ["Wolfgang", "Boy", "German", "\"Wolf path\"", "VOLF-gahng"],
    ["Rudolph", "Boy", "Germanic", "\"Famous wolf\"", "ROO-dolf"],
    ["Rolf", "Boy", "German", "Short form of Rudolf", "ROLF"],
    ["Siegfried", "Boy", "German", "\"Victory\" + \"peace\"", "ZEEK-freet"],
    ["Dietrich", "Boy", "German", "\"Ruler of the people\"", "DEE-trikh"],
    ["Arnold", "Boy", "Germanic", "\"Eagle power\"", "AR-nuld"],
    ["Anselm", "Boy", "Germanic", "\"Divine helmet\"", "AN-selm"],
    ["Ernst", "Boy", "German", "\"Serious, earnest\"", "AIRNST"],
    ["Roland", "Boy", "Germanic", "\"Famous land\"", "RO-lund"],
    ["Raymond", "Boy", "Germanic", "\"Wise protector\"", "RAY-mund"],
    ["Bruno", "Boy", "Germanic", "\"Brown\"", "BROO-no"],
    ["Hans", "Boy", "German", "Short form of Johannes (John)", "HAHNS"],
    ["Klaus", "Boy", "German", "Short form of Nikolaus", "KLOWSS"],
    ["Ulrich", "Boy", "German", "\"Prosperity and power\"", "OOL-rikh"],
    ["Emmerich", "Boy", "German", "Probably \"work ruler\"; the source of the Italian name Amerigo", "EM-uh-rikh"],
   ],
   "after": ["Many of these are names of courage and strength. For more, see [baby names meaning brave](/blog/names-meaning-brave/) and [strong baby boy names](/blog/strong-baby-boy-names/)."]},
  {"h": "What German Parents Choose Today",
   "before": [
    "The names above are the German classics, but they are not what you would hear on a German playground today. Current favorites in Germany are short and international: **Emilia, Emma, Mia, Sophia, Hannah, and Lina** for girls, and **Noah, Matteo, Elias, Leon, Paul, and Luca** for boys. Most of those are not Germanic in origin at all.",
    "At the same time, some grandparent names are returning, just as they are in English. **Frieda, Ida, Greta, Mathilda, and Lotte** are in fashion again for girls, along with **Oskar, Emil, Anton, Theo, and Karl** for boys.",
    "So you have two honest options. If you want a name that sounds German to English ears, choose from the classics. If you want a name a child in Berlin might actually have today, choose from the revival list.",
   ]},
  {"h": "Pronunciation Tips",
   "before": [
    "**W is pronounced like V.** Wolfgang is VOLF-gahng and Wilhelm is VIL-helm.",
    "**A final -e is pronounced.** Lotte is LOT-teh, not \"lot.\" Anneliese ends in -zeh.",
    "**S before a vowel sounds like Z.** Siegfried begins with a Z sound, and Liesel is LEE-zel.",
    "**The -ich and -ig endings are soft.** In Dietrich, Ulrich, and Ludwig, the ending is a soft, breathy sound that English does not have. English speakers usually replace it with a K, which is widely accepted.",
    "If your family will use the English pronunciation, that is perfectly fine. Just decide early, so that grandparents, teachers, and the child all use the same one.",
   ]},
 ],
 "faq": [
  ["What are strong German boy names?", "Conrad (bold counsel), Leopold (bold people), Bernard (brave as a bear), Richard (brave ruler), and Walter (ruler of the army) all carry meanings of strength or leadership. Otto and Hugo are shorter options with the same classic feel."],
  ["What are pretty German girl names?", "Greta, Frieda, Matilda, Liesel, Lotte, and Romy are widely liked. Adelaide and Wilhelmina are longer, more formal choices with the short forms Heidi and Mina."],
  ["What are the most popular baby names in Germany?", "Recent favorites in Germany include Emilia, Emma, Mia, Sophia, and Hannah for girls, and Noah, Matteo, Elias, Leon, and Paul for boys. Rankings change each year and vary between regions."],
  ["Why do so many English names come from German?", "English is a Germanic language, and many Germanic names were also brought to England by the Normans after 1066. William, Henry, Robert, Richard, Emma, and Alice all arrived that way."],
 ],
 "sources": [
  "Behind the Name. [German names](https://www.behindthename.com/names/usage/german).",
  "Gesellschaft für deutsche Sprache. [Die beliebtesten Vornamen](https://gfds.de/vornamen/beliebteste-vornamen/).",
  "Oxford University Press. *A Dictionary of First Names* (Hanks, Hardcastle, and Hodges).",
 ],
}
