POST = {
 "date": "2026-10-16", "accent": "blue", "cover_word": "Hebrew", "cover_sub": "Classic & modern Israeli names",
 "title": "65 Hebrew Baby Names: Classic and Modern Israeli Names with Meanings",
 "description": "Hebrew baby names for boys and girls, from classics like Ezra and Naomi to modern Israeli favorites like Noa, Lior, and Tal, with meanings and pronunciation.",
 "tags": ["hebrew baby names", "israeli baby names", "jewish baby names", "hebrew girl names", "hebrew boy names", "baby names"],
 "intro": [
  "Hebrew has given English more first names than almost any other language. Michael, Sarah, Daniel, Hannah, and Elizabeth are so familiar that most people forget they are Hebrew at all.",
  "But there is a second, less familiar group: the names Israeli parents choose today. Many are short, drawn from nature, and used for both boys and girls, such as Noa, Tal, Lior, and Gal. This list covers both groups: 65 names with their meanings and how to say them.",
 ],
 "takeaway": "Hebrew names fall into two broad styles. Biblical names (Ezra, Levi, Naomi, Miriam) are usually built from a phrase about God or a story of the child's birth. Modern Israeli names (Tal, Oren, Aviva, Maayan) are more often plain nature words. If you want something recognizably Hebrew but fresh, the modern group is where to look. For names taken directly from scripture, see our [biblical baby names](/blog/biblical-baby-names/).",
 "sections": [
  {"h": "Modern Hebrew Girl Names",
   "rows": [
    ["Noa", "Girl", "Hebrew", "\"Movement\"; a biblical name and a long-time favorite in Israel. Not related to the boy's name Noah", "NO-ah"],
    ["Talia", "Girl", "Hebrew", "\"Dew from God\"", "TAHL-yah"],
    ["Shira", "Girl", "Hebrew", "\"Song, poetry\"", "SHEE-rah"],
    ["Aviva", "Girl", "Hebrew", "\"Spring\"", "ah-VEE-vah"],
    ["Liora", "Girl", "Hebrew", "\"My light\"", "lee-OR-ah"],
    ["Orly", "Girl", "Hebrew", "\"Light for me\"", "OR-lee"],
    ["Yael", "Girl", "Hebrew", "\"Ibex, mountain goat\"", "yah-EL"],
    ["Ayelet", "Girl", "Hebrew", "\"Doe, gazelle\"", "ah-YEH-let"],
    ["Tamar", "Girl", "Hebrew", "\"Date palm\"", "tah-MAR"],
    ["Ilana", "Girl", "Hebrew", "\"Tree\"", "ee-LAH-nah"],
    ["Dalia", "Girl", "Hebrew", "\"Hanging branch\"", "DAHL-yah"],
    ["Hadassah", "Girl", "Hebrew", "\"Myrtle tree\"; the Hebrew name of Queen Esther", "hah-DAH-sah"],
    ["Shoshana", "Girl", "Hebrew", "\"Lily\" or \"rose\"; the source of Susan and Susanna", "sho-SHAH-nah"],
    ["Aliza", "Girl", "Hebrew", "\"Joyful\"", "ah-LEE-zah"],
    ["Rina", "Girl", "Hebrew", "\"Joy, song\"", "REE-nah"],
    ["Adina", "Girl", "Hebrew", "\"Delicate, gentle\"", "ah-DEE-nah"],
    ["Eliana", "Girl", "Hebrew", "\"My God has answered\"", "el-ee-AH-nah"],
    ["Chaya", "Girl", "Hebrew", "\"Living, alive\"", "KHAH-yah"],
    ["Keren", "Girl", "Hebrew", "\"Ray of light\"; also \"horn\"", "KEH-ren"],
    ["Hila", "Girl", "Hebrew", "\"Halo\"", "HEE-lah"],
   ]},
  {"h": "Classic Hebrew Girl Names",
   "rows": [
    ["Naomi", "Girl", "Hebrew", "\"Pleasantness\"", "nay-OH-mee"],
    ["Hannah", "Girl", "Hebrew", "\"Grace, favor\"", "HAN-uh"],
    ["Sarah", "Girl", "Hebrew", "\"Princess, noblewoman\"", "SAIR-uh"],
    ["Abigail", "Girl", "Hebrew", "\"My father is joy\"", "AB-ih-gayl"],
    ["Esther", "Girl", "Persian, used in Hebrew", "Probably \"star\"", "ES-ter"],
    ["Ruth", "Girl", "Hebrew", "Probably \"friend, companion\"", "ROOTH"],
    ["Miriam", "Girl", "Hebrew", "Meaning debated; the original form of Mary", "MEER-ee-um"],
    ["Deborah", "Girl", "Hebrew", "\"Bee\"", "DEB-or-uh"],
    ["Elisheva", "Girl", "Hebrew", "\"My God is an oath\"; the original form of Elizabeth", "el-ee-SHEH-vah"],
   ]},
  {"h": "Modern Hebrew Boy Names",
   "rows": [
    ["Ari", "Boy", "Hebrew", "\"Lion\"", "AH-ree"],
    ["Eitan", "Boy", "Hebrew", "\"Strong, enduring\"; the Hebrew form of Ethan", "ay-TAHN"],
    ["Noam", "Boy", "Hebrew", "\"Pleasantness\"", "NO-ahm"],
    ["Oren", "Boy", "Hebrew", "\"Pine tree\"", "OR-en"],
    ["Ilan", "Boy", "Hebrew", "\"Tree\"", "ee-LAHN"],
    ["Aviv", "Boy", "Hebrew", "\"Spring\"", "ah-VEEV"],
    ["Dov", "Boy", "Hebrew", "\"Bear\"", "DOHV"],
    ["Zev", "Boy", "Hebrew", "\"Wolf\"", "ZEV"],
    ["Uri", "Boy", "Hebrew", "\"My light, my flame\"", "OO-ree"],
    ["Matan", "Boy", "Hebrew", "\"Gift\"", "mah-TAHN"],
    ["Nadav", "Boy", "Hebrew", "\"Generous\"", "nah-DAHV"],
    ["Ronen", "Boy", "Hebrew", "\"Joyful song\"", "ro-NEN"],
    ["Omer", "Boy", "Hebrew", "\"Sheaf of grain\"", "OH-mer"],
    ["Itai", "Boy", "Hebrew", "\"With me\"", "ee-TYE"],
    ["Idan", "Boy", "Hebrew", "\"Era, time\"", "ee-DAHN"],
   ]},
  {"h": "Classic Hebrew Boy Names",
   "rows": [
    ["Ezra", "Boy", "Hebrew", "\"Help\"", "EZ-ruh"],
    ["Levi", "Boy", "Hebrew", "\"Joined, attached\"", "LEE-vye"],
    ["Asher", "Boy", "Hebrew", "\"Happy, blessed\"", "ASH-er"],
    ["Elijah", "Boy", "Hebrew", "\"My God is Yahweh\"", "ee-LYE-juh"],
    ["Micah", "Boy", "Hebrew", "\"Who is like God?\"", "MY-kuh"],
    ["Jonah", "Boy", "Hebrew", "\"Dove\"", "JO-nuh"],
    ["Gideon", "Boy", "Hebrew", "\"One who cuts down, hewer\"", "GID-ee-un"],
    ["Amos", "Boy", "Hebrew", "\"Carried, borne\"", "AY-mus"],
    ["Isaac", "Boy", "Hebrew", "\"He will laugh\"", "EYE-zik"],
    ["Raphael", "Boy", "Hebrew", "\"God has healed\"", "RAF-ay-el"],
    ["Ezekiel", "Boy", "Hebrew", "\"God strengthens\"", "ih-ZEE-kee-ul"],
    ["Judah", "Boy", "Hebrew", "\"Praised\"", "JOO-duh"],
    ["Simon", "Boy", "Hebrew", "\"He has heard\"", "SY-mun"],
   ],
   "after": ["Several of these carry the idea of a child who was asked for or given. For more, see [names that mean miracle, gift, or blessing](/blog/names-meaning-miracle/)."]},
  {"h": "Unisex Hebrew Names",
   "before": ["Short nature names used for both boys and girls are one of the most distinctive features of modern Israeli naming."],
   "rows": [
    ["Tal", "Unisex", "Hebrew", "\"Dew\"", "TAHL"],
    ["Lior", "Unisex", "Hebrew", "\"My light\"", "lee-OR"],
    ["Gal", "Unisex", "Hebrew", "\"Wave\"", "GAHL"],
    ["Shai", "Unisex", "Hebrew", "\"Gift\"", "SHY"],
    ["Ariel", "Unisex", "Hebrew", "\"Lion of God\"", "ah-ree-EL"],
    ["Zohar", "Unisex", "Hebrew", "\"Radiance, brilliance\"", "ZO-har"],
    ["Maayan", "Unisex", "Hebrew", "\"Spring of water\"", "mah-ah-YAHN"],
    ["Yuval", "Unisex", "Hebrew", "\"Stream\"", "yoo-VAHL"],
   ],
   "after": ["For more options in this style, see our [gender-neutral baby names](/blog/gender-neutral-baby-names/)."]},
  {"h": "Pronunciation Notes Before You Choose",
   "before": [
    "**Stress usually falls on the last syllable.** In Hebrew it is tah-MAR, ay-TAHN, and lee-OR. English speakers tend to stress the first syllable instead, so decide which version you will use at home.",
    "**The \"ch\" is not the ch in chair.** In names like Chaya and Chaim, it is a throaty sound made at the back of the mouth, closer to the ch in the Scottish word *loch*. It is often written *kh*. If nobody in your family makes this sound naturally, the name will usually be said with a plain h.",
    "**Noa and Noah are different names.** Noa (נֹעָה) is a girl's name meaning movement. Noah (נֹחַ) is a boy's name meaning rest. They are spelled differently in Hebrew and come from different roots.",
    "**Naming customs differ between communities.** Ashkenazi Jewish families traditionally name a child after a relative who has passed away, while many Sephardi families name after living grandparents. If the name is meant to honor your heritage, it is worth asking your family which custom they follow.",
   ]},
 ],
 "faq": [
  ["What are popular Hebrew baby names right now?", "In Israel, short modern names such as Noa, Tamar, Maya, Ari, Noam, and Uri are widely used. In English-speaking countries, the classic Hebrew names Ezra, Levi, Asher, Elijah, and Naomi have all been rising."],
  ["What Hebrew name means light?", "Lior and Liora mean my light, Orly means light for me, Uri means my light or my flame, and Zohar means radiance. All come from the Hebrew word or, meaning light."],
  ["What are unisex Hebrew names?", "Tal (dew), Lior (my light), Gal (wave), Shai (gift), Ariel (lion of God), and Maayan (spring of water) are used for both boys and girls in Israel."],
  ["Are Noa and Noah the same name?", "No. Noa is a girl's name meaning movement, and Noah is a boy's name meaning rest. They have different spellings and roots in Hebrew, even though they look almost identical in English."],
 ],
 "sources": [
  "Behind the Name. [Hebrew names](https://www.behindthename.com/names/usage/hebrew).",
  "Israel Central Bureau of Statistics. [Most common given names](https://www.cbs.gov.il/en/).",
  "Oxford University Press. *A Dictionary of First Names* (Hanks, Hardcastle, and Hodges).",
 ],
}
