POST = {
 "date": "2026-10-27", "accent": "gold", "cover_word": "Sun", "cover_sub": "Names meaning sun, sunshine & dawn",
 "title": "45 Baby Names That Mean Sun, Sunshine, or Dawn",
 "description": "Baby names that mean sun, sunshine, or dawn from Greek, Sanskrit, Japanese, Persian, Welsh, and more, with origins, meanings, and pronunciation for boys and girls.",
 "tags": ["names meaning sun", "names meaning sunshine", "names meaning dawn", "sun baby names", "celestial baby names", "baby names"],
 "intro": [
  "Almost every culture has a name for the sun, and almost every culture has turned it into a name for a child. That makes sun names unusually varied: you can choose something as familiar as Sunny or Aurora, or as rare as Heulwen or Inti.",
  "Below are 45 names that mean sun, sunshine, or dawn, grouped by meaning. Each includes its language of origin and a pronunciation guide, since many of these will be new to English speakers.",
 ],
 "takeaway": "If you want a sun name that is easy to use in English, look at Sol, Elio, Soleil, Ravi, and Aurora. If you want something rare, Welsh (Heulwen), Armenian (Arev), and Quechua (Inti) each have a simple word for sun that works as a name. To complete the sky, see our lists of [names meaning moon](/blog/names-meaning-moon/) and [names meaning star](/blog/names-meaning-star/).",
 "sections": [
  {"h": "Girl Names That Mean Sun or Sunshine",
   "rows": [
    ["Soleil", "Girl", "French", "\"Sun\"", "so-LAY"],
    ["Sunny", "Girl", "English", "\"Sunny, cheerful\"", "SUN-ee"],
    ["Helia", "Girl", "Greek", "Feminine form of Helios, \"sun\"", "HEE-lee-uh"],
    ["Sunniva", "Girl", "Old English, via Norwegian", "\"Sun gift\"", "SOO-nee-vah"],
    ["Heulwen", "Girl", "Welsh", "\"Sunshine\"; from *heul*, sun, and *gwen*, white or blessed", "HAYL-wen"],
    ["Marisol", "Girl", "Spanish", "A blend of María and Soledad; popularly understood as \"sea and sun\"", "mah-ree-SOHL"],
    ["Elanor", "Girl", "Sindarin (Tolkien)", "\"Sun-star\"; a small golden flower in *The Lord of the Rings*", "EL-uh-nor"],
    ["Savitri", "Girl", "Sanskrit", "\"Relating to the sun\"; from the sun deity Savitr", "SAH-vee-tree"],
    ["Hina", "Girl", "Japanese", "Often written 陽菜, \"sunlight\" + \"greens\"", "hee-nah"],
    ["Yoko", "Girl", "Japanese", "When written 陽子, \"sun child\"", "yoh-koh"],
    ["Arevik", "Girl", "Armenian", "\"Little sun\"", "ah-reh-VEEK"],
    ["Shamsa", "Girl", "Arabic", "Feminine form of Shams, \"sun\"", "SHAM-sah"],
    ["Sorina", "Girl", "Romanian", "From *soare*, \"sun\"", "so-REE-nah"],
    ["Sunshine", "Girl", "English", "Sunlight", "SUN-shine"],
   ]},
  {"h": "Boy Names That Mean Sun",
   "rows": [
    ["Elio", "Boy", "Italian / Spanish", "From Helios, \"sun\"", "EL-ee-oh"],
    ["Helios", "Boy", "Greek", "\"Sun\"; the Greek god who drove the sun across the sky", "HEE-lee-ohs"],
    ["Ravi", "Boy", "Sanskrit", "\"Sun\"", "RAH-vee"],
    ["Surya", "Boy", "Sanskrit", "\"Sun\"; the Hindu sun god", "SOOR-yah"],
    ["Aditya", "Boy", "Sanskrit", "\"Belonging to Aditi\"; a name of the sun god", "ah-DIT-yah"],
    ["Mihir", "Boy", "Sanskrit", "\"Sun\"", "mih-HEER"],
    ["Samson", "Boy", "Hebrew", "From *shemesh*, \"sun\"", "SAM-sun"],
    ["Shams", "Boy", "Arabic", "\"Sun\"", "SHAMS"],
    ["Aftab", "Boy", "Persian / Urdu", "\"Sun, sunshine\"", "ahf-TAHB"],
    ["Taiyo", "Boy", "Japanese", "Written 太陽, \"sun\"", "tah-ee-yoh"],
    ["Haruto", "Boy", "Japanese", "Often written 陽翔, \"sunlight\" + \"to soar\"", "hah-roo-toh"],
    ["Sorin", "Boy", "Romanian", "From *soare*, \"sun\"", "so-REEN"],
    ["Arev", "Boy", "Armenian", "\"Sun\"", "ah-REV"],
    ["Inti", "Boy", "Quechua", "\"Sun\"; the sun god of the Inca", "IN-tee"],
    ["Ra", "Boy", "Egyptian", "The ancient Egyptian sun god", "RAH"],
    ["Apollo", "Boy", "Greek", "The god of light, music, and healing, later identified with the sun. The origin of the name itself is uncertain", "uh-POL-oh"],
   ],
   "after": ["Japanese names change meaning with the characters used to write them. Haruto and Hina can be written in other ways that have nothing to do with the sun. See our [Japanese baby names](/blog/japanese-baby-names/) for how this works."]},
  {"h": "More Sun Names",
   "rows": [
    ["Sol", "Unisex", "Spanish / Latin", "\"Sun\"", "SOHL"],
    ["Hinata", "Unisex", "Japanese", "Often written 日向, \"sunny place, facing the sun\"", "hee-nah-tah"],
    ["Haru", "Unisex", "Japanese", "When written 陽, \"sunlight\"; when written 春, \"spring\"", "hah-roo"],
    ["Güneş", "Unisex", "Turkish", "\"Sun\"", "gew-NESH"],
    ["Cyrus", "Boy", "Persian, via Greek", "Origin uncertain; traditionally linked to the Persian word for sun", "SY-rus"],
   ]},
  {"h": "Names That Mean Dawn or Sunrise",
   "rows": [
    ["Aurora", "Girl", "Latin", "\"Dawn\"; the Roman goddess of the dawn", "uh-ROR-uh"],
    ["Dawn", "Girl", "English", "Daybreak", "DAWN"],
    ["Zora", "Girl", "Slavic", "\"Dawn\"", "ZOR-uh"],
    ["Roxana", "Girl", "Persian, via Greek", "\"Dawn, bright\"", "rok-SAH-nuh"],
    ["Roxanne", "Girl", "Persian, via French", "French form of Roxana", "rok-SAN"],
    ["Anatolia", "Girl", "Greek", "\"Sunrise, the east\"", "an-uh-TOH-lee-uh"],
    ["Anatole", "Boy", "Greek, via French", "\"Sunrise\"", "AN-uh-tohl"],
    ["Arun", "Boy", "Sanskrit", "\"Reddish-brown, dawn\"; the charioteer of the sun", "uh-ROON"],
    ["Eos", "Girl", "Greek", "\"Dawn\"; the Greek goddess of the dawn", "EE-ohs"],
    ["Alba", "Girl", "Italian / Spanish", "\"Dawn\"", "AHL-bah"],
   ]},
  {"h": "How to Choose a Sun Name",
   "before": [
    "**Pair it with the season.** A sun name suits a summer baby, but it can be even more meaningful for a baby born in the darkest part of winter, close to the solstice, when the days begin to lengthen again.",
    "**Check the spelling against the sound.** Soleil is said so-LAY and Heulwen is HAYL-wen. If a name is not pronounced the way it looks in English, be ready to spell it and say it often.",
    "**Consider a sun and moon pair for siblings or twins.** Sol and Luna, Elio and Selene, and Ravi and Chandra are matching pairs without being matching sounds. Our [twin baby name pairs](/blog/twin-baby-name-pairs/) guide has more.",
    "**Be careful with names from living religious traditions.** Surya, Aditya, and Savitri are names of deities who are actively worshipped. They are common given names in Hindu families, and using them with respect means knowing what they refer to.",
    "You can try first and middle name combinations in our [Baby Name Generator](/tools/name-generator/).",
   ]},
 ],
 "faq": [
  ["What girl name means sun?", "Soleil is French for sun, Helia is the feminine form of the Greek word for sun, and Sunniva means sun gift. Heulwen is Welsh for sunshine, and Arevik is Armenian for little sun."],
  ["What boy name means sun?", "Elio and Helios come from the Greek word for sun. Ravi, Surya, and Mihir mean sun in Sanskrit, Shams means sun in Arabic, and Samson comes from the Hebrew word for sun."],
  ["What name means sunshine?", "Heulwen is the Welsh word for sunshine, and Aftab means sun or sunshine in Persian and Urdu. In English, Sunny and Sunshine are both used as given names."],
  ["What names mean dawn?", "Aurora is Latin for dawn, Zora is Slavic, Alba is Italian and Spanish, and Eos is Greek. Roxana comes from a Persian word meaning dawn or bright."],
 ],
 "sources": [
  "Behind the Name. [Name etymologies and histories](https://www.behindthename.com/).",
  "Oxford University Press. *A Dictionary of First Names* (Hanks, Hardcastle, and Hodges).",
  "U.S. Social Security Administration. [Popular Baby Names](https://www.ssa.gov/oact/babynames/).",
 ],
}
