POST = {
 "date": "2026-10-21", "accent": "lilac", "cover_word": "Moon", "cover_sub": "Names meaning moon & moonlight",
 "title": "40 Baby Names That Mean Moon",
 "description": "40 baby names that mean moon or moonlight for girls and boys, from Luna and Selene to Aylin, Mahina, Badr, and Chandra, with origins, meanings, and pronunciation.",
 "tags": ["names meaning moon", "moon baby names", "celestial baby names", "luna names", "girl names", "boy names"],
 "intro": [
  "Luna has been one of the fastest-rising girl names of the past decade, and it has sent many parents looking for other names with the same meaning. There are plenty, because nearly every language has used its word for the moon as a name.",
  "This list has 40 names that mean moon, moonlight, full moon, or crescent, along with the moon gods and goddesses whose names are still in use. Each entry has its origin and a pronunciation guide.",
 ],
 "takeaway": "If you love Luna but want something less common, look at the same word in other languages: Mahina (Hawaiian), Marama (Maori), Aylin (Turkish), Lusine (Armenian), and Chandra (Sanskrit) all mean moon. Arabic is unusually precise, with separate names for the moon (Qamar), the full moon (Badr), and the crescent (Hilal). To complete the sky, see [names meaning sun](/blog/names-meaning-sun/) and [names meaning star](/blog/names-meaning-star/).",
 "sections": [
  {"h": "Girl Names That Mean Moon",
   "rows": [
    ["Luna", "Girl", "Latin", "\"Moon\"; the Roman goddess of the moon", "LOO-nuh"],
    ["Selene", "Girl", "Greek", "\"Moon\"; the Greek goddess of the moon", "seh-LEE-nee"],
    ["Selena", "Girl", "Greek, via Latin", "Form of Selene", "seh-LEE-nuh"],
    ["Artemis", "Girl", "Greek", "The goddess of the hunt and the moon; the meaning of the name is unknown", "AR-teh-mis"],
    ["Diana", "Girl", "Latin", "\"Divine\"; the Roman goddess of the hunt and the moon", "dye-AN-uh"],
    ["Cynthia", "Girl", "Greek", "\"From Mount Cynthus\"; a title of Artemis", "SIN-thee-uh"],
    ["Aylin", "Girl", "Turkish", "\"Moon halo\"", "eye-LEEN"],
    ["Ayla", "Girl", "Turkish", "\"Moonlight, halo\"", "EYE-lah"],
    ["Aysel", "Girl", "Turkish / Azerbaijani", "\"Moon stream\"", "eye-SEL"],
    ["Mahina", "Girl", "Hawaiian", "\"Moon\"", "mah-HEE-nah"],
    ["Marama", "Girl", "Maori", "\"Moon\"", "MAH-rah-mah"],
    ["Purnima", "Girl", "Sanskrit", "\"Full moon\"", "POOR-nee-mah"],
    ["Mahtab", "Girl", "Persian", "\"Moonlight\"", "mah-TAHB"],
    ["Mizuki", "Girl", "Japanese", "Often written 美月, \"beautiful moon\"", "mee-zoo-kee"],
    ["Tsukiko", "Girl", "Japanese", "Written 月子, \"moon child\"", "tsoo-kee-koh"],
    ["Yue", "Girl", "Chinese", "When written 月, \"moon\"", "YWEH"],
    ["Nguyệt", "Girl", "Vietnamese", "\"Moon\"", "NGWEE-et"],
    ["Hằng", "Girl", "Vietnamese", "From Hằng Nga, the moon goddess", "HAHNG"],
    ["Lusine", "Girl", "Armenian", "From *lusin*, \"moon\"", "loo-SEE-neh"],
    ["Levana", "Girl", "Hebrew", "\"Moon\"; literally \"the white one\"", "leh-vah-NAH"],
   ]},
  {"h": "Boy Names That Mean Moon",
   "rows": [
    ["Badr", "Boy", "Arabic", "\"Full moon\"", "BAH-der"],
    ["Hilal", "Boy", "Arabic", "\"Crescent moon\"", "hee-LAHL"],
    ["Rakesh", "Boy", "Sanskrit", "\"Lord of the full-moon night\"", "rah-KAYSH"],
    ["Shashank", "Boy", "Sanskrit", "\"Moon\"; literally \"marked with a hare\"", "shuh-SHAHNK"],
    ["Chandran", "Boy", "Tamil / Malayalam", "Form of Chandra, \"moon\"", "CHUN-drun"],
    ["Aibek", "Boy", "Kazakh / Kyrgyz", "\"Moon\" + \"lord\"", "eye-BEK"],
    ["Aydin", "Boy", "Turkish", "\"Bright, enlightened\"; from *ay*, \"moon\"", "eye-DIN"],
    ["Koray", "Boy", "Turkish", "\"Ember moon\"", "ko-RYE"],
    ["Mani", "Boy", "Old Norse", "The moon, personified as a god in Norse myth", "MAH-nee"],
    ["Khonsu", "Boy", "Egyptian", "\"Traveler\"; the Egyptian god of the moon", "KON-soo"],
    ["Iah", "Boy", "Egyptian", "\"Moon\"; an Egyptian moon god", "EE-ah"],
    ["Jericho", "Boy", "Hebrew", "A place name, possibly \"city of the moon\"", "JER-ih-ko"],
   ]},
  {"h": "Unisex Names That Mean Moon",
   "rows": [
    ["Chandra", "Unisex", "Sanskrit", "\"Moon\"; the Hindu moon god", "CHUN-druh"],
    ["Qamar", "Unisex", "Arabic", "\"Moon\"", "KAH-mar"],
    ["Shashi", "Unisex", "Sanskrit", "\"Moon\"", "SHUH-shee"],
    ["Soma", "Unisex", "Sanskrit", "A name of the moon and its god", "SO-mah"],
    ["Chan", "Unisex", "Thai", "\"Moon\"", "JAHN"],
    ["Bulan", "Unisex", "Indonesian / Malay", "\"Moon\"", "BOO-lahn"],
    ["Meztli", "Unisex", "Nahuatl", "\"Moon\"", "MESS-tlee"],
    ["Ilargi", "Unisex", "Basque", "\"Moon\"", "ee-LAR-gee"],
   ],
   "after": ["For more options that work for any child, see our [gender-neutral baby names](/blog/gender-neutral-baby-names/)."]},
  {"h": "How to Choose a Moon Name",
   "before": [
    "**If you like Luna, check how common it is where you live.** Luna has been near the top of the charts in many countries. That is not a reason to avoid it, but your daughter may well share it with a classmate. Selene, Mahina, and Aylin give you the same meaning with far fewer of them around.",
    "**Decide between the word and the goddess.** Luna, Mahina, and Qamar are simply the word for moon. Artemis, Diana, and Cynthia are names of a goddess associated with the moon, and their literal meanings are something else.",
    "**Check names written in characters.** Mizuki and Yue only mean moon when written with the character 月. The same sounds can be written with other characters that mean something entirely different. Our [Japanese baby names](/blog/japanese-baby-names/) and [Chinese baby names](/blog/chinese-baby-names/) guides explain how this works.",
    "**Consider a sun and moon pair for twins or siblings.** Sol and Luna, Helios and Selene, and Ravi and Chandra match in meaning without sounding alike. See our [twin baby name pairs](/blog/twin-baby-name-pairs/).",
    "You can try first and middle name combinations in our [Baby Name Generator](/tools/name-generator/).",
   ]},
 ],
 "faq": [
  ["What girl name means moon?", "Luna is Latin for moon and Selene is Greek. Mahina means moon in Hawaiian, Marama in Maori, and Lusine comes from the Armenian word for moon. Aylin is a Turkish name meaning moon halo."],
  ["What boy name means moon?", "Badr means full moon and Hilal means crescent moon in Arabic. Rakesh and Shashank are Sanskrit names for the moon, and Aibek combines the Turkic word for moon with a word meaning lord."],
  ["What names are similar to Luna?", "Selene and Selena share the meaning and a similar sound. Mahina, Marama, Aylin, and Ayla are other short names that mean moon or moonlight."],
  ["What name means moonlight?", "Mahtab means moonlight in Persian, and Ayla is a Turkish name meaning moonlight or halo."],
 ],
 "sources": [
  "Behind the Name. [Name etymologies and histories](https://www.behindthename.com/).",
  "Oxford University Press. *A Dictionary of First Names* (Hanks, Hardcastle, and Hodges).",
  "U.S. Social Security Administration. [Popular Baby Names](https://www.ssa.gov/oact/babynames/).",
 ],
}
