# 多篇清單文共用的更正（同一個名字在不同文章應該寫同一個含義）
COMMON = {
 "Ace": (None, None, None, "One; the highest card"),
 "Bo": (None, None, None, "To live"),
 "Cole": (None, None, None, "Charcoal; swarthy"),
 "Ezra": (None, None, None, "Help"),
 "Finn": (None, None, None, "Fair, white"),
 "Hugo": (None, None, None, "Mind, spirit"),
 "Ivan": (None, None, None, "Slavic form of John, 'God is gracious'"),
 "Jack": (None, None, None, "Medieval pet form of John, 'God is gracious'"),
 "Liam": (None, None, None, "Short form of William, 'resolute protector'"),
 "Luke": (None, None, None, "From Lucania"),
 "Max": (None, None, None, "Short form of Maximilian, 'greatest'"),
 "Zane": (None, None, "English", "Meaning uncertain; sometimes explained as a form of John"),
 "Ada": (None, None, None, "Noble"),
 "Alma": (None, None, None, "Nourishing; in Spanish, 'soul'"),
 "Aria": (None, None, None, "Air; a solo song in opera"),
 "Bea": (None, None, None, "Short form of Beatrice, 'she who brings happiness'"),
 "Cleo": (None, None, None, "Glory; short form of Cleopatra"),
 "Ella": (None, None, None, "From a Germanic word meaning 'all'; also a short form of Eleanor"),
 "Faye": (None, None, None, "Fairy"),
 "June": (None, None, None, "The month of June, named for the goddess Juno"),
 "Kate": (None, None, None, "Short form of Katherine"),
 "Leah": (None, None, None, "Possibly 'weary'"),
 "Mae": (None, None, None, "A form of May; also a pet form of Mary or Margaret"),
 "Mia": (None, None, "Scandinavian / Italian", "Pet form of Maria; in Italian, 'mine'"),
 "Nora": (None, None, None, "Short form of Honora, 'honor', or of Eleanor"),
 "Opal": (None, None, None, "Gem, jewel"),
 "Tess": (None, None, None, "Short form of Theresa"),
 "Blake": (None, None, None, "Dark; or pale"),
 "Bree": (None, None, None, "Short form of Bridget or Brianna"),
 "Quinn": (None, None, None, "From Conn, 'chief' or 'intelligence'"),
 "Drew": (None, None, None, "Short form of Andrew, 'manly, brave'"),
 "Tate": (None, None, None, "Possibly 'cheerful'"),
 "Maeve": (None, None, None, "She who intoxicates"),
 "Alexander": (None, None, None, "Defender of men"),
 "Henry": (None, None, None, "Home ruler"),
 "Samuel": (None, None, None, "God has heard"),
 "Nathaniel": (None, None, None, "God has given"),
 "Leonidas": (None, None, None, "Lion-like"),
 "Caspian": (None, None, "English", "Of the Caspian Sea"),
 "Kai": (None, None, "Hawaiian", "Sea"),
 "Cyrus": (None, None, None, "Meaning uncertain; the founder of the Persian Empire"),
 "Gideon": (None, None, None, "One who cuts down, hewer"),
 "Caleb": (None, None, None, "Meaning uncertain; often given as 'whole-hearted'"),
 "Isaiah": (None, None, None, "Yahweh is salvation"),
 "Joshua": (None, None, None, "Yahweh is salvation"),
 "Silas": (None, None, None, "From Silvanus, 'of the forest'"),
 "Axel": (None, None, "Scandinavian", "Scandinavian form of Absalom, 'father of peace'"),
 "Bode": (None, None, "German", "Messenger"),
 "Titan": (None, None, None, "The Titans, the elder gods of Greek myth"),
 "Alaric": (None, None, None, "Ruler of all"),
 "Amias": (None, None, None, "Possibly from Latin amatus, 'loved'"),
 "Bastian": (None, None, None, "Short form of Sebastian, from a Greek word meaning 'venerable'"),
 "Caius": (None, None, None, "Uncertain; possibly related to Latin gaudere, 'to rejoice'"),
 "Dashiell": (None, None, None, "From a French surname; meaning uncertain"),
 "Idris": (None, None, None, "In Welsh, 'ardent lord'; in Arabic, the name of a prophet"),
 "Iskander": (None, None, None, "A form of Alexander, 'defender of men'"),
 "Jorvik": (None, None, None, "The Old Norse name for the city of York"),
 "Kael": (None, None, None, "From Irish caol, 'slender'"),
 "Marcellus": (None, None, None, "Little Marcus; dedicated to Mars"),
 "Oberon": (None, None, None, "King of the fairies in Shakespeare; probably 'elf ruler'"),
 "Quillon": (None, None, None, "From the French word for the crossguard of a sword"),
 "Soren": (None, None, None, "Danish form of Severinus, 'stern'"),
 "Vesper": (None, None, None, "Evening; the evening star"),
 "Xander": (None, None, None, "Short form of Alexander, 'defender of men'"),
 "Cassius": (None, None, None, "From a Roman family name, possibly 'hollow'"),
 "Brielle": (None, None, None, "Short form of Gabrielle, 'God is my strength'"),
 "Ondine": (None, None, None, "From Latin unda, 'wave'"),
 "Ottilie": (None, None, None, "Wealth, fortune"),
 "Seraphina": (None, None, None, "From the seraphim, 'the burning ones'"),
 "Xiomara": (None, None, None, "Possibly 'famous in battle'"),
 "Charlotte": (None, None, None, "French feminine form of Charles, 'free man'"),
 "Isabella": (None, None, "Italian / Spanish", "A form of Elizabeth, 'my God is an oath'"),
 "Eleanor": (None, None, "French", "Meaning uncertain"),
 "Amelia": (None, None, None, "From a Germanic word meaning 'work'"),
 "Genevieve": (None, None, None, "Meaning uncertain; possibly 'woman of the people'"),
 "Penelope": (None, None, None, "Possibly 'weaver'"),
 "Cordelia": (None, None, None, "Uncertain; sometimes explained as 'daughter of the sea'"),
 "Mira": (None, None, "Latin / Slavic", "Wonderful; in Slavic languages, 'peace'"),
 "Lumi": (None, None, None, "Snow"),
 "Aoife": (None, None, None, "Beauty, radiance"),
 "Calla": (None, None, None, "Beauty; also the calla lily"),
 "Soraya": (None, None, None, "The Pleiades, a cluster of stars"),
 "Aiyana": (None, None, "Uncertain", "Often given as 'eternal blossom'; the origin is uncertain"),
 "Yara": (None, None, "Tupi / Arabic", "In Tupi legend, 'lady of the water'; also used in Arabic"),
 "Suri": (None, None, None, "In Persian, 'red rose'; also a Yiddish form of Sarah"),
 "Indie": (None, None, None, "Short form of India or Indiana"),
 "Lennox": (None, None, None, "Place of elms"),
 "Eden": (None, None, None, "Delight"),
 "Eli": (None, None, None, "High, ascended"),
}
