ROWS = {
 "Aiden": (None, None, None, "Little fire"),
 "Caelum": (None, None, None, "Sky, heaven; also a constellation"),
 "Darwin": (None, None, None, "Dear friend"),
 "Edison": (None, None, None, "From an English surname; the name of inventor Thomas Edison"),
 "Finn": (None, None, None, "Fair, white"),
 "Galileo": (None, None, None, "From Galilee; the name of the astronomer"),
 "Hudson": (None, None, None, "Son of Hugh"),
 "Idris": (None, None, None, "In Welsh, 'ardent lord'; in Arabic, the name of a prophet"),
 "Jove": (None, None, None, "Jupiter, the Roman king of the gods"),
 "Kai": (None, None, "Hawaiian", "Sea"),
 "Leo": (None, None, None, "Lion"),
 "Miles": (None, None, None, "Meaning uncertain; often linked to Latin miles, 'soldier'"),
 "Noel": (None, None, None, "Christmas"),
 "Orion": (None, None, None, "Meaning uncertain; the hunter constellation"),
 "Phoenix": (None, None, None, "Dark red; the mythical bird reborn from fire"),
 "Rainer": (None, None, None, "Counsel + army"),
 "Skyler": (None, None, "Dutch", "From the Dutch surname Schuyler, 'scholar'"),
 "Wade": (None, None, None, "Ford, river crossing"),
 "Xander": (None, None, None, "Short form of Alexander, 'defender of men'"),
 "Zephyr": (None, None, None, "West wind"),
 "Cedric": (None, None, "English", "Coined by Sir Walter Scott for Ivanhoe; meaning uncertain"),
 "Brooks": (None, None, None, "Of the brook"),
 "Novak": (None, None, None, "New man, newcomer"),
 "Aquata": ("Aqua", None, "Latin", "Water"),
 "Celeste": (None, None, None, "Heavenly"),
 "Delta": (None, None, None, "The mouth of a river; the fourth Greek letter"),
 "Eden": (None, None, None, "Delight"),
 "Freya": (None, None, None, "Lady; the Norse goddess of love"),
 "Haven": (None, None, None, "Harbor, safe place"),
 "Juno": (None, None, None, "Queen of the Roman gods; possibly 'youth'"),
 "Kaia": (None, None, None, "Scandinavian pet form of Katarina; also linked to Hawaiian kai, 'sea'"),
 "Neve": (None, None, None, "In Italian, 'snow'; also an English spelling of Niamh, 'bright'"),
 "Phoebe": (None, None, None, "Bright, radiant"),
 "Rain": (None, None, None, "Rain"),
 "Skye": (None, None, None, "From the Isle of Skye in Scotland"),
 "Tallulah": (None, None, None, "Often given as 'leaping water'; from a place name in Georgia"),
 "Unity": (None, None, None, "Oneness"),
 "Vera": (None, None, None, "Faith; also Latin for 'true'"),
 "Xenia": (None, None, None, "Hospitality"),
 "Zora": (None, None, None, "Dawn"),
 "Astrid": (None, None, None, "Divinely beautiful"),
 "Lyra": (None, None, None, "Lyre; the constellation Lyra"),
}
PROSE = []
