ROWS = {
 "Ares": (None, None, None, "The Greek god of war"),
 "Blaze": (None, None, None, "Flame"),
 "Marcus": (None, None, None, "Dedicated to Mars, the god of war"),
 "Aiden": (None, None, None, "Little fire"),
 "Leo": (None, None, None, "Lion"),
 "Griffin": (None, None, None, "From Gruffudd, 'strong lord'"),
 "Valor": (None, None, None, "Bravery, courage"),
 "Ignatius": (None, None, None, "From a Roman family name; long associated with Latin ignis, 'fire'"),
 "Ryder": (None, None, None, "Rider, horseman"),
 "Phoenix": (None, None, None, "Dark red; the mythical bird reborn from fire"),
 "Brandt": (None, None, "Germanic", "Firebrand, sword"),
 "Everett": (None, None, None, "Brave as a wild boar"),
 "Keegan": (None, None, None, "Son of Egan, 'little fire'"),
 "Maximus": (None, None, None, "Greatest"),
 "Andre": (None, None, None, "French form of Andrew, 'manly, brave'"),
 "Conor": (None, None, None, "Lover of hounds"),
 "Enzo": (None, None, None, "Short form of Lorenzo or Vincenzo; also an Italian form of Henry"),
 "Harlan": (None, None, None, "From an English surname, 'hare land' or 'army land'"),
 "Kieran": (None, None, None, "Little dark one"),
 "Maverick": (None, None, "American English", "An independent person; from rancher Samuel Maverick"),
 "Barrett": (None, None, "English", "From a surname, possibly 'bear strength'"),
 "Ryker": (None, None, "Dutch / German", "From a surname related to the word 'rich'"),
 "Fintan": (None, None, None, "Possibly 'white fire' or 'white bull'"),
 "Zander": (None, None, None, "Short form of Alexander, 'defender of men'"),
 "Valentina": (None, None, None, "Strong, vigorous"),
 "Seraphina": (None, None, None, "From the seraphim, 'the burning ones'"),
 "Brielle": (None, None, None, "Short form of Gabrielle, 'God is my strength'"),
 "Athena": (None, None, None, "The Greek goddess of wisdom and war"),
 "Ember": (None, None, None, "A glowing coal"),
 "Freya": (None, None, None, "Lady; the Norse goddess of love and war"),
 "Bridget": (None, None, None, "Exalted one; the Irish goddess of fire and poetry"),
 "Andrea": (None, None, None, "Feminine form of Andrew, 'manly, brave'"),
 "Brenna": (None, None, None, "From an Irish surname; often given as 'raven'"),
 "Fiamma": (None, None, None, "Flame"),
 "Kira": (None, None, None, "Russian feminine form of Cyrus"),
 "Marcella": (None, None, None, "Feminine form of Marcus, 'dedicated to Mars'"),
 "Nadia": (None, None, "Russian", "Short form of Nadezhda, 'hope'"),
 "Soleil": (None, None, None, "Sun"),
 "Adira": (None, None, None, "Strong, mighty"),
 "Calida": (None, None, None, "Warm"),
 "Enya": (None, None, None, "Anglicized form of Eithne, 'kernel'"),
 "Thea": (None, None, None, "Short form of Dorothea or Theodora; also Theia, the Titan goddess of light"),
 "Maeve": (None, None, None, "She who intoxicates; the warrior queen of Irish legend"),
 "Ramona": (None, None, None, "Feminine form of Raymond, 'wise protector'"),
 "Signe": (None, None, None, "New victory"),
 "Valeria": (None, None, None, "Strong, healthy"),
 "Zara": (None, None, None, "Possibly from Arabic zahrah, 'blossom'"),
 "Rhea": (None, None, None, "Mother of the Greek gods; possibly 'flowing'"),
}
PROSE = []
