ROWS = {
 "Aaron": (None, None, None, "Meaning uncertain; often given as 'exalted'"),
 "Abel": (None, None, None, "Breath"),
 "Caleb": (None, None, None, "Meaning uncertain; often given as 'whole-hearted'"),
 "Ezra": (None, None, None, "Help"),
 "Gideon": (None, None, None, "One who cuts down, hewer"),
 "Isaiah": (None, None, None, "Yahweh is salvation"),
 "Jacob": (None, None, None, "Supplanter; holder of the heel"),
 "Jeremiah": (None, None, None, "Yahweh will exalt"),
 "Jesse": (None, None, None, "Possibly 'gift'"),
 "Joshua": (None, None, None, "Yahweh is salvation"),
 "Josiah": (None, None, None, "Yahweh supports"),
 "Lucas": (None, None, None, "From Lucania"),
 "Silas": (None, None, None, "From Silvanus, 'of the forest'"),
 "Solomon": (None, None, None, "Peace"),
 "Abigail": (None, None, None, "My father is joy"),
 "Damaris": (None, None, None, "Possibly 'calf'"),
 "Deborah": (None, None, None, "Bee"),
 "Delilah": (None, None, None, "Delicate"),
 "Esther": (None, None, None, "Probably 'star'"),
 "Elizabeth": (None, None, None, "My God is an oath"),
 "Judith": (None, None, None, "Woman of Judea"),
 "Leah": (None, None, None, "Possibly 'weary'"),
 "Lydia": (None, None, None, "From Lydia, a region of Asia Minor"),
 "Mary": (None, None, None, "From Hebrew Miriam; meaning uncertain"),
 "Miriam": (None, None, None, "Meaning uncertain"),
 "Rachel": (None, None, None, "Ewe"),
 "Rebecca": (None, None, None, "Possibly 'to bind'"),
 "Ruth": (None, None, None, "Probably 'friend'"),
 "Selah": (None, None, None, "A word from the Psalms, possibly 'pause'"),
 "Shiloh": (None, None, None, "Uncertain; often given as 'tranquil'"),
 "Jordan": (None, None, None, "To flow down; the river Jordan"),
}
PROSE = []
