ROWS = {
 "Dylan": (None, None, None, "Great tide"),
 "Adrian": (None, None, None, "From Hadria, the town that gave the Adriatic Sea its name"),
 "Morgan": (None, None, None, "Possibly 'sea chief' or 'sea circle'"),
 "Noah": (None, None, None, "Rest, comfort"),
 "Kai": (None, None, None, "Sea"),
 "Lachlan": (None, None, None, "From the land of lakes; originally a name for a Norseman"),
 "Nereus": (None, None, None, "A Greek god of the sea"),
 "Caspian": (None, None, "English", "Of the Caspian Sea"),
 "Irving": (None, None, None, "Green water, fresh water"),
 "Brooks": (None, None, None, "Of the brook"),
 "Dorian": (None, None, None, "Of the Dorians, an ancient Greek people"),
 "Kelvin": (None, None, None, "From the River Kelvin in Scotland"),
 "Murphy": (None, None, None, "Sea warrior"),
 "Beckett": (None, None, None, "From an English surname, possibly 'little brook'"),
 "Corin": (None, None, None, "From Quirinus, possibly 'spear'"),
 "Edmund": (None, None, None, "Rich protector"),
 "Fidel": (None, None, None, "Faithful"),
 "Gideon": (None, None, None, "One who cuts down, hewer"),
 "Hartley": (None, None, None, "Stag clearing"),
 "Jasper": (None, None, None, "Treasurer"),
 "Liam": (None, None, None, "Short form of William, 'resolute protector'"),
 "Osmond": (None, None, None, "Divine protector"),
 "Rafael": (None, None, None, "God has healed"),
 "Soren": (None, None, "Danish", "Danish form of Severinus, 'stern'"),
 "Warren": (None, None, "English, from Norman French", "From a Norman place name; also linked to a Germanic word for 'guard'"),
 "Luna": (None, None, None, "Moon"),
 "Marina": (None, None, None, "Of the sea"),
 "Cordelia": (None, None, None, "Uncertain; sometimes explained as 'daughter of the sea'"),
 "Selene": (None, None, None, "Moon; the Greek goddess of the moon"),
 "Pearl": (None, None, None, "Pearl"),
 "Maren": (None, None, "Danish", "Danish form of Marina, 'of the sea'"),
 "Diana": (None, None, None, "Divine; the Roman goddess of the moon"),
 "Nerida": (None, None, None, "From the Nereids, the sea nymphs"),
 "Isla": (None, None, None, "From Islay, a Scottish island"),
 "Oceane": (None, None, None, "Ocean"),
 "Phoebe": (None, None, None, "Bright, radiant; a Titan linked with the moon"),
 "Rosemary": (None, None, None, "The herb; from Latin for 'dew of the sea'"),
 "Serena": (None, None, None, "Serene, calm"),
 "Tallulah": (None, None, None, "Often given as 'leaping water'; from a place name in Georgia"),
 "Undine": (None, None, None, "From Latin unda, 'wave'"),
 "Vivian": (None, None, None, "Alive"),
 "Waverly": (None, None, None, "Meadow of quivering aspens"),
 "Yara": (None, None, "Tupi / Arabic", "In Tupi legend, 'lady of the water'; also used in Arabic"),
 "Zarya": (None, None, None, "Dawn"),
 "Amara": (None, None, None, "In Igbo, 'grace'; in Sanskrit, 'immortal'"),
 "Brynn": (None, None, None, "Hill"),
 "Celeste": (None, None, None, "Heavenly"),
 "Daphne": (None, None, None, "Laurel"),
 "Estelle": (None, None, None, "Star"),
 "Haven": (None, None, None, "Harbor, safe place"),
}
PROSE = []
