ROWS = {
 "Conrad": (None, None, None, "Bold counsel"),
 "Edmund": (None, None, None, "Rich protector"),
 "Flint": (None, None, None, "A hard stone"),
 "Barrett": (None, None, "English", "From a surname, possibly 'bear strength'"),
 "Callum": (None, None, None, "Dove"),
 "Garrison": (None, None, None, "Son of Garret; also a fortified post"),
 "Desmond": (None, None, None, "From South Munster, a region of Ireland"),
 "Cedric": (None, None, "English", "Coined by Sir Walter Scott for Ivanhoe; meaning uncertain"),
 "Everest": (None, None, None, "From an English surname; the name of the world's highest mountain"),
 "Garrett": (None, None, None, "From Gerard or Gerald: spear + 'brave' or 'ruler'"),
 "Aldric": (None, None, None, "Old ruler"),
 "Bernard": (None, None, None, "Brave as a bear"),
 "Clayton": (None, None, None, "Settlement on clay"),
 "Emery": (None, None, None, "From a name ending in ric, 'power'"),
 "Henry": (None, None, None, "Home ruler"),
 "Marcus": (None, None, None, "Dedicated to Mars"),
 "Nolan": (None, None, None, "From an Irish surname meaning 'noble, famous'"),
 "Quentin": (None, None, None, "Fifth"),
 "Thaddeus": (None, None, None, "Meaning uncertain; possibly 'heart'"),
 "Warren": (None, None, "English, from Norman French", "From a Norman place name; also linked to a Germanic word for 'guard'"),
 "Arthur": (None, None, None, "Meaning uncertain, possibly 'bear'"),
 "Bridget": (None, None, None, "Exalted one"),
 "Sierra": (None, None, None, "Mountain range; literally 'saw'"),
 "Elara": (None, None, None, "A figure in Greek myth and a moon of Jupiter; meaning uncertain"),
 "Honora": (None, None, None, "Honor"),
 "Millicent": (None, None, None, "Work + strength"),
 "Brynn": (None, None, None, "Hill"),
 "Adelaide": (None, None, None, "Noble kind"),
 "Greta": (None, None, "German", "Short form of Margarete, 'pearl'"),
 "Hildegard": (None, None, None, "Battle + enclosure"),
 "Edith": (None, None, None, "Rich in war"),
 "Maura": (None, None, None, "Irish form of Mary; also from Latin Maurus, 'dark'"),
 "Theresa": (None, None, None, "Meaning uncertain; possibly 'harvest' or 'summer'"),
 "Vivienne": (None, None, None, "Alive"),
 "Willa": (None, None, None, "Feminine form of William, 'resolute protector'"),
 "Harriet": (None, None, None, "Feminine form of Henry, 'home ruler'"),
 "Daphne": (None, None, None, "Laurel"),
 "Imogen": (None, None, None, "Probably 'maiden'"),
}
PROSE = []
