ROWS = {
 "Antoine": (None, None, None, "French form of Anthony, from a Roman family name of uncertain meaning"),
 "Bastien": (None, None, None, "Short form of Sébastien, from a Greek word meaning 'venerable'"),
 "Emile": (None, None, None, "From the Roman family name Aemilius, 'rival'"),
 "Etienne": (None, None, None, "French form of Stephen, 'crown'"),
 "Gaspard": (None, None, None, "Treasurer"),
 "Henri": (None, None, None, "Home ruler"),
 "Hugo": (None, None, None, "Mind, spirit"),
 "Jacques": (None, None, None, "French form of Jacob and James, 'supplanter'"),
 "Laurent": (None, None, None, "From Laurentum"),
 "Mathis": (None, None, None, "French form of Matthias, 'gift of God'"),
 "Remi": (None, None, None, "From Latin Remigius, 'oarsman'"),
 "Sebastien": (None, None, None, "From Sebaste; from a Greek word meaning 'venerable'"),
 "Theo": (None, None, None, "Short form of Théodore, 'gift of God'"),
 "Tristan": (None, None, None, "From the Celtic name Drustan; linked by legend to French triste, 'sad'"),
 "Adele": (None, None, None, "Noble"),
 "Amelie": (None, None, None, "From a Germanic word meaning 'work'"),
 "Charlotte": (None, None, None, "French feminine form of Charles, 'free man'"),
 "Colette": (None, None, None, "Short form of Nicolette, 'victory of the people'"),
 "Eloise": (None, None, None, "Meaning uncertain; possibly Germanic, 'healthy' + 'wide'"),
 "Genevieve": (None, None, None, "Meaning uncertain; possibly 'woman of the people'"),
 "Madeleine": (None, None, None, "From Magdala, a town whose name means 'tower'"),
 "Simone": (None, None, None, "French feminine form of Simon, 'he has heard'"),
 "Vivienne": (None, None, None, "Alive"),
 "Francis": (None, None, None, "Frenchman; later understood as 'free one'"),
 "Morgan": (None, None, None, "Possibly 'sea chief' or 'sea circle'; Welsh in origin"),
}
PROSE = []
