ROWS = {
 "Hugo": (None, None, "Germanic", "Mind, spirit"),
 "Felix": (None, None, None, "Lucky, happy"),
 "Caspian": (None, None, "English", "Of the Caspian Sea"),
 "Sage": (None, None, None, "Wise; also the herb"),
 "Alaric": (None, None, "Gothic", "Ruler of all"),
 "Corbin": (None, None, None, "Raven"),
 "Dashiell": (None, None, None, "From a French surname; meaning uncertain"),
 "Emrys": (None, None, None, "Immortal; the Welsh form of Ambrose"),
 "Hermes": (None, None, None, "The messenger of the Greek gods"),
 "Luca": (None, None, None, "Italian form of Luke, 'from Lucania'"),
 "Orion": (None, None, None, "Meaning uncertain; the hunter constellation"),
 "Phineas": (None, None, None, "Meaning uncertain; possibly Egyptian, 'the Nubian'"),
 "Quinn": (None, None, None, "From Conn, 'chief' or 'intelligence'"),
 "Rafferty": (None, None, None, "From an Irish surname meaning 'prosperity'"),
 "Stellan": (None, None, "Swedish", "Possibly 'calm'"),
 "Theron": (None, None, None, "Hunter"),
 "Vincent": (None, None, None, "Conquering"),
 "Wyatt": (None, None, None, "Brave in war"),
 "Caelum": (None, None, None, "Sky, heaven"),
 "Idris": (None, None, "Welsh / Arabic", "In Welsh, 'ardent lord'; in Arabic, the name of a prophet"),
 "Jasper": (None, None, None, "Treasurer"),
 "Kellan": (None, None, None, "From an Irish surname, possibly 'slender'"),
 "Leander": (None, None, None, "Lion man"),
 "Aria": (None, None, None, "Air; a solo song in opera"),
 "Clio": (None, None, None, "Glory; the muse of history"),
 "Elara": (None, None, None, "A figure in Greek myth and a moon of Jupiter; meaning uncertain"),
 "Gemma": (None, None, None, "Gem, jewel"),
 "Juno": (None, None, None, "Queen of the Roman gods; possibly 'youth'"),
 "Kaia": (None, None, None, "Scandinavian pet form of Katarina; also linked to Hawaiian kai, 'sea'"),
 "Luna": (None, None, None, "Moon"),
 "Mira": (None, None, "Latin / Slavic", "Wonderful; in Slavic languages, 'peace'"),
 "Nova": (None, None, None, "New"),
 "Ophelia": (None, None, None, "Help"),
 "Paloma": (None, None, None, "Dove"),
 "Rhea": (None, None, None, "Mother of the Greek gods; possibly 'flowing'"),
 "Seren": (None, None, None, "Star"),
 "Thalia": (None, None, None, "To blossom; the muse of comedy"),
 "Una": (None, None, "Latin / Irish", "In Latin, 'one'; the Irish name Úna may mean 'lamb'"),
 "Vera": (None, None, None, "Faith; also Latin for 'true'"),
 "Wren": (None, None, None, "A small songbird"),
 "Xanthe": (None, None, None, "Golden, yellow"),
 "Yara": (None, None, "Tupi / Arabic", "In Tupi legend, 'lady of the water'; also used in Arabic"),
 "Zelda": (None, None, "Germanic", "Short form of Griselda, 'gray battle'"),
 "Astrid": (None, None, None, "Divinely beautiful"),
 "Calliope": (None, None, None, "Beautiful voice; the muse of epic poetry"),
 "Daphne": (None, None, None, "Laurel"),
 "Eloise": (None, None, None, "Meaning uncertain; possibly Germanic, 'healthy' + 'wide'"),
}
PROSE = []
