ROWS = {
 "Alexandros": (None, None, None, "Defender of men"),
 "Andreas": (None, None, None, "Manly, brave"),
 "Dimitrios": (None, None, None, "Devoted to Demeter"),
 "Leonidas": (None, None, None, "Lion-like"),
 "Odysseus": (None, None, None, "Meaning uncertain, possibly 'wrathful'; the hero of the Odyssey"),
 "Orion": (None, None, None, "Meaning uncertain; the hunter constellation"),
 "Thanos": (None, None, None, "Short form of Athanasios, 'immortal'"),
 "Yannis": (None, None, None, "Greek form of John, 'God is gracious'"),
 "Aikaterini": (None, None, None, "Meaning uncertain; long associated with katharos, 'pure'"),
 "Alexandra": (None, None, None, "Defender of men"),
 "Athena": (None, None, None, "The goddess of wisdom"),
 "Cassandra": (None, None, None, "Meaning uncertain; the prophetess of Troy"),
 "Daphne": (None, None, None, "Laurel"),
 "Eleni": (None, None, None, "Greek form of Helen; probably 'torch' or 'shining light'"),
 "Katerina": (None, None, None, "Short form of Aikaterini"),
 "Melina": (None, None, None, "Honey"),
 "Penelope": (None, None, None, "Possibly 'weaver'; the faithful wife of Odysseus"),
 "Thalia": (None, None, None, "To blossom; the muse of comedy"),
 "Alexis": (None, None, None, "Helper, defender"),
 "Paris": (None, None, None, "Meaning uncertain; the prince of Troy"),
 "Thanasis": (None, None, None, "Short form of Athanasios, 'immortal'"),
}
PROSE = []
