ROWS = {
 "Aarav": (None, None, None, "Often given as 'peaceful'"),
 "Aditya": (None, None, None, "Belonging to Aditi; a name of the sun god"),
 "Gautam": (None, None, None, "Descendant of Gotama; the family name of the Buddha"),
 "Ishaan": (None, None, None, "A name of Shiva; guardian of the northeast"),
 "Kabir": (None, None, "Arabic", "Great") if False else (None, None, None, "Great; from Arabic"),
 "Krishna": (None, None, None, "Dark, black"),
 "Rohan": (None, None, None, "Ascending"),
 "Sahil": (None, None, None, "Shore, coast; from Arabic"),
 "Siddharth": (None, None, None, "One who has accomplished his goal"),
 "Vivaan": (None, None, None, "Often given as 'full of life'; a modern name"),
 "Aanya": (None, None, None, "Often given as 'inexhaustible'; a modern name"),
 "Anita": (None, None, None, "Grace; a form of Anna widely used in India"),
 "Kiara": (None, None, None, "Used in India; from Irish Ciara, 'dark-haired', or Italian Chiara, 'bright'"),
 "Maya": (None, None, None, "Illusion"),
 "Meera": (None, None, None, "The name of the poet-saint Mirabai; meaning uncertain"),
 "Nisha": (None, None, None, "Night"),
 "Riya": (None, None, None, "Often given as 'singer'"),
 "Saanvi": (None, None, None, "Often given as a name of the goddess Lakshmi"),
 "Sara": (None, None, None, "Princess; from Hebrew, widely used in India"),
 "Tara": (None, None, None, "Star"),
 "Zara": (None, None, None, "Possibly from Arabic zahrah, 'blossom'"),
 "Arya": (None, None, None, "Noble"),
 "Daksha": (None, None, None, "Skilled, able"),
 "Indra": (None, None, None, "King of the gods in Hindu tradition; meaning uncertain"),
 "Neel": (None, None, None, "Blue"),
}
PROSE = [("> 💡 **Tip:** The most popular Indian baby names right now include", "> 💡 **Tip:** Widely used Indian baby names in recent years include")]
