ROWS = {
 "Brendan": (None, None, None, "Prince"),
 "Cillian": (None, None, None, "Little church; or 'strife'"),
 "Cormac": (None, None, None, "Possibly 'son of the charioteer'"),
 "Declan": (None, None, None, "Meaning uncertain; often given as 'full of goodness'"),
 "Eamon": (None, None, None, "Irish form of Edmund, 'rich protector'"),
 "Eoin": (None, None, None, "Irish form of John, 'God is gracious'"),
 "Fergus": (None, None, None, "Man of vigor"),
 "Liam": (None, None, None, "Short form of Uilliam (William), 'resolute protector'"),
 "Niall": (None, None, None, "Possibly 'champion' or 'cloud'"),
 "Padraig": (None, None, None, "Irish form of Patrick, 'nobleman'"),
 "Sean": (None, None, None, "Irish form of John, 'God is gracious'"),
 "Tadhg": (None, None, None, "Poet", "TYG (like 'tiger' without the 'er')"),
 "Aoife": (None, None, None, "Beauty, radiance"),
 "Bridget": (None, None, None, "Exalted one"),
 "Deirdre": (None, None, None, "Meaning uncertain; linked by legend to sorrow"),
 "Eimear": (None, None, None, "Possibly 'swift'"),
 "Grainne": (None, None, None, "Possibly from grán, 'grain'"),
 "Nora": (None, None, None, "Short form of Honora, 'honor', or of Eleanor"),
 "Siobhan": (None, None, None, "Irish form of Joan, 'God is gracious'"),
 "Sinead": (None, None, None, "Irish form of Janet, 'God is gracious'"),
 "Sorcha": (None, None, None, "Bright, radiant", "SUR-uh-kha"),
 "Darcy": (None, None, None, "From the Irish surname Ó Dorchaidhe, 'dark one'; also Norman d'Arcy"),
 "Quinn": (None, None, None, "From Conn, 'chief' or 'intelligence'"),
 "Riley": (None, None, None, "Often given as 'valiant'; also English 'rye clearing'"),
 "Shannon": (None, None, None, "From the River Shannon, possibly 'old' or 'wise one'"),
 "Tierney": (None, None, None, "Lord"),
}
PROSE = []
