ROWS = {
 "Daichi": (None, None, None, "Usually written 大地, 'great earth'"),
 "Eiji": (None, None, None, "Often written 英二, 'excellent' + 'second son'"),
 "Haruki": (None, None, None, "Often written 春樹, 'spring' + 'tree'"),
 "Hiroshi": (None, None, None, "Generous, broad"),
 "Kaito": (None, None, None, "Often written 海斗 or 海翔, beginning with 'sea'"),
 "Kenji": (None, None, None, "Often written 健二 or 賢二, 'healthy' or 'wise' + 'second son'"),
 "Ryo": (None, None, None, "Often written 涼, 'cool, refreshing', or 亮, 'bright'"),
 "Takeshi": (None, None, None, "Usually written 武, 'warrior'"),
 "Yamato": (None, None, None, "Great harmony; an old name for Japan"),
 "Yuto": (None, None, None, "Often written 悠斗 or 優斗; 悠 means 'distant, leisurely' and 優 means 'gentle'"),
 "Aiko": (None, None, None, "Usually written 愛子, 'child of love'"),
 "Akemi": (None, None, None, "Often written 明美, 'bright' + 'beautiful'"),
 "Ayumi": (None, None, None, "Often written 歩, 'walk, progress'"),
 "Emi": (None, None, None, "Often written 恵美, 'blessing' + 'beauty'"),
 "Haruka": (None, None, None, "Often written 遥, 'distant'"),
 "Himari": (None, None, None, "Often written 陽葵, 'sun' + 'hollyhock'"),
 "Koharu": (None, None, None, "Written 小春, 'little spring'; the word also means a warm spell in late autumn"),
 "Mei": (None, None, None, "Often written 芽依 or 芽生, beginning with 'sprout'"),
 "Mio": (None, None, None, "Often written 美桜, 'beautiful cherry blossom', or 澪, 'waterway'"),
 "Natsuki": (None, None, None, "Often written 夏希, 'summer' + 'hope', or 菜月, 'greens' + 'moon'"),
 "Rin": (None, None, None, "Often written 凛, 'dignified'"),
 "Saki": (None, None, None, "Often written 咲, 'to blossom'"),
 "Yui": (None, None, None, "Often written 結衣, 'to tie' + 'garment'"),
 "Yuna": (None, None, None, "Often written 優奈 or 結菜; the meaning depends on the characters"),
 "Aoi": (None, None, None, "Written 葵, 'hollyhock', or 碧, 'blue-green'"),
}
PROSE = []
