ROWS = {
 "Leo": (None, None, None, "Lion"),
 "Leon": (None, None, None, "Lion"),
 "Arthur": (None, None, None, "Meaning uncertain, possibly 'bear'; the legendary king of Britain"),
 "Rex": (None, None, None, "King"),
 "Cyrus": (None, None, None, "Meaning uncertain; the founder of the Persian Empire"),
 "Apollo": (None, None, None, "The Greek god of light, music, and the sun"),
 "Alaric": (None, None, "Gothic", "Ruler of all"),
 "Alaric#2": ("Lionel", None, "French", "Little lion"),
 "Augustus": (None, None, None, "Venerable, majestic"),
 "Felix": (None, None, None, "Lucky, happy"),
 "Griffin": (None, None, None, "From Gruffudd, 'strong lord'"),
 "Henry": (None, None, "Germanic", "Home ruler"),
 "Jasper": (None, None, None, "Treasurer"),
 "Kingston": (None, None, None, "King's town"),
 "Leopold": (None, None, "Germanic", "Bold people"),
 "Magnus": (None, None, None, "Great"),
 "Orion": (None, None, None, "Meaning uncertain; the hunter constellation"),
 "Patrick": (None, None, None, "Nobleman, patrician"),
 "Quentin": (None, None, None, "Fifth"),
 "Regis": (None, None, None, "Of the king"),
 "Samson": (None, None, None, "From shemesh, 'sun'"),
 "Solomon": (None, None, None, "Peace; the wise king of the Bible"),
 "Bastian": (None, None, None, "Short form of Sebastian, from a Greek word meaning 'venerable'"),
 "Darius": (None, None, None, "Possessing goodness; the name of Persian kings"),
 "Emeric": (None, None, "Germanic", "From a name ending in ric, 'ruler, power'"),
 "Leona": (None, None, None, "Lioness"),
 "Aurora": (None, None, None, "Dawn"),
 "Regina": (None, None, None, "Queen"),
 "Solana": (None, None, None, "Sunny place"),
 "Eleonora": (None, None, "Italian", "Italian form of Eleanor; meaning uncertain"),
 "Aurelia": (None, None, None, "Golden"),
 "Victoria": (None, None, None, "Victory"),
 "Helena": (None, None, None, "Form of Helen; probably 'torch' or 'shining light'"),
 "Marisol": (None, None, None, "A blend of María and Soledad; popularly understood as 'sea and sun'"),
 "Orla": (None, None, None, "Golden princess"),
 "Queenie": (None, None, None, "Queen"),
 "Roxana": (None, None, None, "Dawn, bright"),
 "Savannah": (None, None, "Spanish, from Taino", "A treeless plain"),
 "Thea": (None, None, None, "Short form of Dorothea or Theodora; also Theia, the Titan goddess of light"),
 "Valentina": (None, None, None, "Strong, vigorous"),
 "Winifred": (None, None, None, "Blessed peace"),
 "Xiomara": (None, None, None, "Possibly 'famous in battle'"),
 "Yolanda": (None, None, "Spanish", "Probably 'violet'"),
 "Zara": (None, None, None, "Possibly from Arabic zahrah, 'blossom'"),
 "Ariadne": (None, None, None, "Most holy"),
 "Beatrix": (None, None, None, "She who brings happiness"),
 "Cleopatra": (None, None, None, "Glory of the father"),
 "Dahlia": (None, None, "Swedish, via botany", "The dahlia flower, named for botanist Anders Dahl"),
 "Elara": (None, None, None, "A figure in Greek myth and a moon of Jupiter; meaning uncertain"),
 "Goldie": (None, None, None, "Gold"),
}
PROSE = []
