ROWS = {
 "Jasper": (None, None, None, "Treasurer"),
 "Cedric": (None, None, "English", "Coined by Sir Walter Scott for Ivanhoe; meaning uncertain"),
 "Alaric": (None, None, "Gothic", "Ruler of all"),
 "Adonis": (None, None, None, "Lord; the beautiful youth of Greek myth"),
 "Asa": (None, None, None, "Possibly 'healer'"),
 "Caius": (None, None, None, "Uncertain; possibly related to Latin gaudere, 'to rejoice'"),
 "Stellan": (None, None, None, "Possibly 'calm'"),
 "Lorcan": (None, None, None, "Little fierce one"),
 "Geoffrey": (None, None, None, "A Germanic name ending in frid, 'peace'"),
 "Emeric": (None, None, None, "From a name ending in ric, 'ruler, power'"),
 "Shiloh": (None, None, None, "Uncertain; often given as 'tranquil'"),
 "Cassius": (None, None, None, "From a Roman family name, possibly 'hollow'"),
 "Dorian": (None, None, None, "Of the Dorians, an ancient Greek people"),
 "Ren": (None, None, None, "'Lotus' when written 蓮; 'love' when written 恋"),
 "Harmony": (None, None, None, "Harmony"),
 "Grace": (None, None, None, "Grace"),
 "Freya": (None, None, None, "Lady; the Norse goddess of love"),
 "Mira": (None, None, None, "Wonderful; in Slavic languages, 'peace'"),
 "Winifred": (None, None, None, "Blessed peace"),
 "Eir": (None, None, None, "Mercy; the Norse goddess of healing"),
 "Galena": (None, None, None, "Calm"),
 "Naomi": (None, None, None, "Pleasantness"),
 "Halcyon": (None, None, None, "Kingfisher; calm and peaceful"),
}
PROSE = []
