ROWS = {
 "Jasper": (None, None, None, "Treasurer; also a red-brown gemstone"),
 "Heath": (None, None, None, "Heathland"),
 "Forrest": (None, None, None, "Of the forest"),
 "Clay": (None, None, None, "Clay, earth"),
 "Linden": (None, None, None, "The linden tree"),
 "Orion": (None, None, None, "Meaning uncertain; the hunter of Greek myth and a constellation"),
 "Brooks": (None, None, None, "Of the brook"),
 "Flint": (None, None, None, "A hard stone"),
 "Cedar": (None, None, None, "The cedar tree"),
 "Birch": (None, None, None, "The birch tree"),
 "Cliff": (None, None, None, "Cliff; also short for Clifford, 'ford by a cliff'"),
 "Alder": (None, None, None, "The alder tree"),
 "Stone": (None, None, None, "Stone"),
 "Glen": (None, None, None, "Valley"),
 "Basil": (None, None, None, "Kingly; also the herb"),
 "Ridge": (None, None, None, "Ridge, a long hilltop"),
 "Cove": (None, None, None, "A small sheltered bay"),
 "Hawthorne": (None, None, None, "The hawthorn tree"),
 "Sterling": ("Hawk", None, "English", "The hawk"),
 "Wolf": (None, None, "Germanic", "Wolf"),
 "Willow": (None, None, None, "The willow tree"),
 "Ivy": (None, None, None, "The ivy plant"),
 "Dahlia": (None, None, "Swedish, via botany", "The dahlia flower, named for botanist Anders Dahl"),
 "Hazel": (None, None, None, "The hazel tree"),
 "Violet": (None, None, None, "The violet flower; purple"),
 "Iris": (None, None, None, "Rainbow; also the iris flower"),
 "Magnolia": (None, None, "French, via botany", "The magnolia tree, named for botanist Pierre Magnol"),
 "Fern": (None, None, None, "The fern plant"),
 "Poppy": (None, None, None, "The poppy flower"),
 "Laurel": (None, None, None, "The laurel tree, a symbol of victory"),
 "Coral": (None, None, None, "Coral"),
 "Briar": (None, None, None, "A thorny shrub"),
 "Marigold": (None, None, None, "The golden flower, from 'Mary's gold'"),
 "Clover": (None, None, None, "The clover plant"),
 "Wren": (None, None, None, "A small songbird"),
 "Azalea": (None, None, None, "Dry; the azalea shrub"),
 "Flora": (None, None, None, "Flower; the Roman goddess of flowers and spring"),
 "Terra": (None, None, None, "Earth"),
 "Meadow": (None, None, None, "A field of grass"),
 "Pearl": (None, None, "French, via English", "Pearl"),
 "River": (None, None, None, "River"),
 "Sage": (None, None, None, "Wise; also the herb"),
 "Rowan": (None, None, None, "Little red-haired one; also the rowan tree"),
 "Sky": (None, None, None, "Sky"),
 "Ash": (None, None, None, "The ash tree"),
 "Robin": (None, None, None, "Pet form of Robert, 'bright fame'; also the bird"),
 "Lake": (None, None, None, "Lake"),
 "Oakley": (None, None, None, "Oak meadow"),
 "Ember": (None, None, None, "A glowing coal"),
 "Phoenix": (None, None, None, "Dark red; the mythical bird reborn from fire"),
}
PROSE = []
