ROWS = {
 "Asher": (None, None, None, "Happy, blessed"),
 "Felix": (None, None, None, "Lucky, successful, happy"),
 "Benedict": (None, None, None, "Blessed"),
 "Isaac": (None, None, None, "He will laugh"),
 "Saul": ("Anand", None, "Sanskrit", "Bliss, joy"),
 "Gale": ("Gil", None, "Hebrew", "Joy"),
 "Macario": (None, None, "Greek, via Spanish", "Blessed"),
 "Fausto": (None, None, "Latin, via Italian", "Lucky, fortunate"),
 "Baruch": (None, None, None, "Blessed"),
 "Onni": (None, None, None, "Happiness, luck"),
 "Tayo": (None, None, None, "Worth joy; short for names like Olutayo"),
 "Caius": (None, None, None, "Uncertain; possibly related to Latin gaudere, 'to rejoice'"),
 "Said": (None, None, None, "Happy, lucky"),
 "Bennett": (None, None, "English", "Medieval English form of Benedict, 'blessed'"),
 "Boone": (None, None, None, "Good; a blessing"),
 "Beatrice": (None, None, None, "She who brings happiness; blessed"),
 "Felicity": (None, None, None, "Happiness, good fortune"),
 "Blythe": (None, None, None, "Cheerful, happy"),
 "Allegra": (None, None, None, "Cheerful, lively"),
 "Bliss": (None, None, None, "Perfect happiness"),
 "Gwyneth": (None, None, None, "From Welsh gwyn, 'white, fair, blessed'"),
 "Sachiko": (None, None, None, "Usually written 幸子, 'child of happiness'"),
 "Letitia": (None, None, None, "Joy, gladness"),
 "Beata": (None, None, None, "Blessed"),
 "Hana": (None, None, "Arabic", "Happiness, bliss; in Japanese the same sound means 'flower'"),
 "Merry": (None, None, None, "Cheerful, joyful"),
 "Ada": ("Joy", None, "English", "Joy, delight"),
 "Gioia": (None, None, None, "Joy"),
 "Keiko": (None, None, None, "When written 恵子, 'blessed child'; when written 慶子, 'joyful child'"),
 "Farrah": (None, None, None, "Joy"),
 "Eden": (None, None, None, "Delight, pleasure"),
 "Sunny": (None, None, None, "Sunny, cheerful"),
 "Jesse": ("Hilary", None, "Latin", "Cheerful"),
 "Haven": ("Blessing", None, "English", "A blessing"),
 "Shiloh": ("Le", None, "Chinese", "'Joy' when written 樂"),
 "Noam": (None, None, None, "Pleasantness"),
 "Tashi": (None, None, None, "Good fortune, auspicious"),
 "Ayo": (None, None, None, "Joy"),
 "Lucky": (None, None, None, "Fortunate"),
 "Amani": ("Xin", None, "Chinese", "'Glad, joyful' when written 欣"),
}
PROSE = []
