ROWS = {
 "Aiden": (None, None, None, "Little fire; from the Irish name Aodhán"),
 "Aidan": (None, None, None, "Little fire; from the Irish name Aodhán"),
 "Ignatius": (None, None, None, "From a Roman family name; long associated with Latin ignis, 'fire'"),
 "Kenneth": (None, None, None, "From two Gaelic names meaning 'born of fire' and 'handsome'"),
 "Blaze": (None, None, None, "Flame"),
 "Tyson": (None, None, "English, from French", "Firebrand"),
 "Vulcan": (None, None, None, "The Roman god of fire and the forge"),
 "Agni": (None, None, None, "Fire; the Hindu god of fire"),
 "Egan": (None, None, None, "Little fire"),
 "Fintan": (None, None, None, "Possibly 'white fire' or 'white bull'"),
 "Brenton": (None, None, None, "Bryni's town; the Old English name Bryni means 'flame'"),
 "Hagan": (None, None, None, "From Irish surnames meaning 'little fire' or 'young'"),
 "Keegan": (None, None, None, "Son of Egan, 'little fire'"),
 "Conleth": (None, None, None, "Possibly 'chaste fire'"),
 "Hayden": ("Aodh", None, "Irish", "Fire; the root of Aidan, Egan, and Keegan"),
 "Seraphina": (None, None, None, "From the seraphim, 'the burning ones'"),
 "Bridget": (None, None, None, "Exalted one; the Irish goddess of fire and poetry"),
 "Fiamma": (None, None, None, "Flame"),
 "Calida": (None, None, None, "Warm"),
 "Enya": ("Tanwen", None, "Welsh", "White fire, holy fire"),
 "Pele": (None, None, None, "The Hawaiian goddess of fire and volcanoes"),
 "Soleil": ("Azar", None, "Persian", "Fire"),
 "Adara": ("Iskra", None, "Slavic", "Spark"),
 "Kalama": (None, None, None, "The torch"),
 "Anala": (None, None, "Sanskrit", "Fire"),
 "Hestia": (None, None, None, "Hearth, fireside; the Greek goddess of the hearth"),
 "Edana": (None, None, None, "Feminine form of Aidan, 'little fire'"),
 "Ember": (None, None, None, "A glowing coal"),
 "Phoenix": (None, None, None, "Dark red; the mythical bird reborn from fire"),
 "Ash": (None, None, None, "The ash tree; also what remains after a fire"),
 "Kindle": (None, None, None, "To set alight"),
 "Blaine": ("Flint", "Boy", "English", "A hard stone used to strike a spark"),
 "Flannery": ("Brant", "Boy", "Germanic", "Firebrand, sword"),
 "Kiran": ("Shula", "Girl", "Arabic", "Flame"),
 "Rory": ("Plamen", "Boy", "Bulgarian", "Flame"),
}
PROSE = []
