ROWS = {
 "David": (None, None, None, "Beloved"),
 "Amadeus": (None, None, None, "Lover of God"),
 "Phillip": (None, None, None, "Lover of horses"),
 "Erasmus": (None, None, None, "Beloved"),
 "Leif": ("Caradoc", None, "Welsh", "Beloved, amiable"),
 "Connell": ("Philo", None, "Greek", "Loving, a friend"),
 "Carwyn": (None, None, None, "Blessed love"),
 "Jedidiah": (None, None, None, "Beloved of the Lord"),
 "Amato": (None, None, None, "Beloved"),
 "Habib": (None, None, None, "Beloved, darling"),
 "Lennon": (None, None, None, "From an Irish surname, possibly 'lover, sweetheart'"),
 "Premo": ("Prem", None, "Sanskrit", "Love"),
 "Rudo": (None, None, None, "Love"),
 "Sajan": (None, None, None, "Beloved"),
 "Kaleb": ("Aziz", None, "Arabic", "Beloved, dear; also 'powerful'"),
 "Thierry": ("Dragan", None, "Slavic", "Dear, precious"),
 "Eros": (None, None, None, "Love, desire; the Greek god of love"),
 "Darrell": ("Lyubomir", None, "Slavic", "Love and peace"),
 "Amara": ("Amy", None, "French, via English", "Beloved"),
 "Mila": (None, None, None, "From mil, 'gracious, dear'"),
 "Esme": (None, None, "Old French", "Esteemed, loved"),
 "Aphrodite": (None, None, None, "The Greek goddess of love and beauty"),
 "Cara": (None, None, "Italian / Latin", "Dear, beloved; in Irish, 'friend'"),
 "Amanda": (None, None, None, "Worthy of love, lovable"),
 "Aiko": (None, None, None, "Usually written 愛子, 'child of love'"),
 "Cherish": (None, None, None, "To hold dear"),
 "Priya": (None, None, None, "Beloved, dear"),
 "Milena": (None, None, None, "From mil, 'gracious, dear'"),
 "Venus": (None, None, None, "The Roman goddess of love"),
 "Davina": (None, None, None, "Feminine form of David, 'beloved'"),
 "Carina": (None, None, None, "Dear little one"),
 "Freya": (None, None, None, "Lady; the Norse goddess of love"),
 "Amada": (None, None, None, "Beloved"),
 "Suki": ("Carys", None, "Welsh", "Love"),
 "Kerensa": (None, None, None, "Love"),
 "Amore": (None, None, None, "Love"),
 "Paris": ("Kealoha", None, "Hawaiian", "The loved one"),
 "Denver": ("Ai", None, "Japanese / Chinese", "'Love' when written 愛"),
 "Kama": (None, None, None, "Love, desire"),
 "Darcy": ("Anbu", None, "Tamil", "Love, kindness"),
 "Love": (None, None, None, "Love"),
 "Agape": (None, None, None, "Selfless love"),
 "Milan": (None, None, None, "From mil, 'gracious, dear'"),
 "Vida": ("Davy", None, "English", "Pet form of David, 'beloved'"),
 "Amory": ("Amias", "Boy", "Latin, via English", "Possibly from amatus, 'loved'"),
}
PROSE = []
