ROWS = {
 "Lucas": (None, None, "Greek, via Latin", "From Lucania; often associated with Latin lux, 'light'"),
 "Aaron": ("Elior", None, "Hebrew", "My God is my light"),
 "Robert": (None, None, "Germanic", "Bright fame"),
 "Lucian": (None, None, None, "From Lucius, 'light'"),
 "Beacon": (None, None, None, "A signal light"),
 "Oran": ("Meir", None, "Hebrew", "One who gives light"),
 "Abner": (None, None, None, "My father is a light"),
 "Anwar": (None, None, None, "Brighter, more luminous"),
 "Pradeep": (None, None, None, "Lamp, light"),
 "Uriel": (None, None, None, "God is my light"),
 "Chand": ("Kiran", None, "Sanskrit", "Ray of light"),
 "Lucius": (None, None, None, "Light"),
 "Sheridan": ("Nuri", None, "Arabic", "My light"),
 "Bertram": (None, None, "Germanic", "Bright raven"),
 "Mishal": (None, None, None, "Torch"),
 "Lucy": (None, None, None, "Light"),
 "Nora": ("Liora", None, "Hebrew", "My light"),
 "Elena": (None, None, None, "Form of Helen; probably 'torch' or 'shining light'"),
 "Claire": (None, None, None, "Clear, bright"),
 "Lucia": (None, None, None, "Light"),
 "Dawn": (None, None, None, "Daybreak, first light"),
 "Elaine": (None, None, None, "Old French form of Helen, probably 'shining light'"),
 "Phoebe": (None, None, None, "Bright, radiant"),
 "Chiara": (None, None, None, "Italian form of Clara, 'bright, clear'"),
 "Thea": (None, None, None, "Short form of Dorothea; also Theia, the Titan goddess of light"),
 "Zara": ("Roshni", None, "Hindi, from Persian", "Light, brightness"),
 "Ilona": (None, None, None, "Hungarian form of Helen, probably 'shining light'"),
 "Niamh": (None, None, None, "Bright, radiant"),
 "Svetlana": (None, None, None, "From the Slavic word for light"),
 "Hikari": (None, None, None, "Light"),
 "Lux": (None, None, None, "Light"),
 "Noor": (None, None, None, "Light"),
 "Bodhi": (None, None, None, "Awakening, enlightenment"),
 "Raya": ("Roshan", None, "Persian", "Bright, shining"),
 "Ori": (None, None, None, "My light"),
 "Arun": (None, None, None, "Dawn; the charioteer of the sun"),
 "Kira": ("Lior", None, "Hebrew", "My light"),
 "Lucerne": (None, None, None, "Lamp; also a city in Switzerland"),
 "Nur": (None, None, None, "Light"),
 "Aster": ("Zia", None, "Arabic", "Light, glow"),
}
PROSE = []
