ROWS = {
 "Alexander": (None, None, None, "Defender of men"),
 "Marcus": (None, None, None, "Dedicated to Mars, the god of war"),
 "Gunnar": (None, None, None, "Battle warrior"),
 "Duncan": (None, None, None, "Brown warrior"),
 "Oscar": (None, None, "Irish / Old English", "Deer friend; or 'spear of the gods'"),
 "Callan": (None, None, None, "From cath, 'battle'"),
 "Magnus": ("Herman", None, "Germanic", "Army man, soldier"),
 "Finley": (None, None, None, "Fair warrior"),
 "Cadel": (None, None, None, "Battle"),
 "Kane": (None, None, None, "From cath, 'battle'"),
 "Evander": ("Ivor", None, "Norse", "Bow warrior"),
 "Hector": (None, None, None, "Holding fast; the great warrior of Troy"),
 "Igor": (None, None, "Russian, from Norse", "Warrior of the god Ing"),
 "Luther": (None, None, "Germanic", "People's army"),
 "Odin": (None, None, None, "Frenzy, inspiration; the Norse god of war and wisdom"),
 "Troy": (None, None, None, "From an Irish surname meaning 'foot soldier'; also the ancient city"),
 "Louisa": (None, None, "Germanic", "Feminine form of Louis, 'famous warrior'"),
 "Marcella": (None, None, None, "Feminine form of Marcus, 'dedicated to Mars'"),
 "Matilda": (None, None, "Germanic", "Mighty in battle"),
 "Brynhild": (None, None, None, "Armor + battle"),
 "Alessia": (None, None, None, "Defender"),
 "Camilla": (None, None, None, "A warrior maiden in Virgil's Aeneid; the meaning of the name is uncertain"),
 "Zelda": (None, None, "Germanic", "Short form of Griselda, 'gray battle'"),
 "Harlow": (None, None, None, "Army hill"),
 "Minka": ("Hilda", None, "Germanic", "Battle"),
 "Thora": ("Gunhild", None, "Norse", "War + battle"),
 "Kaida": ("Hedwig", None, "Germanic", "Battle, combat"),
 "Ailsa": ("Imelda", None, "Germanic, via Spanish", "Whole battle"),
 "Bellatrix": (None, None, None, "Female warrior"),
 "Sasha": (None, None, None, "Pet form of Alexander or Alexandra, 'defender of men'"),
 "Sloane": (None, None, None, "Raider"),
 "Blair": (None, None, None, "Field, plain; often given as 'battlefield'"),
 "Rory": ("Lou", None, "French / English", "Short form of Louis or Louise, 'famous warrior'"),
 "Kelly": (None, None, None, "From an Irish surname, possibly 'warrior' or 'bright-headed'"),
 "Harley": ("Armani", None, "Italian, from Germanic", "From Herman, 'army man'"),
 "Dustin": ("Miles", "Boy", "English", "Often linked to Latin miles, 'soldier'"),
 "Casey": ("Alex", None, "Greek", "Short form of Alexander or Alexandra, 'defender of men'"),
 "Murphy": (None, None, None, "Sea warrior"),
 "Kendall": ("Nakoa", "Boy", "Hawaiian", "The warriors, the brave ones"),
 "Regan": ("Tyr", "Boy", "Norse", "The Norse god of war"),
}
PROSE = [
 ("> 💡 **Tip: Trending Picks** — Odin, Sloane, Zelda, and Finley are the warrior names generating the most excitement in 2026. They combine mythology and history with a thoroughly modern sound, appealing to parents who want names with depth and edge.",
  "> 💡 **Tip: Hidden Warriors** — Louisa, Matilda, Zelda, and Finley sound gentle, but each one comes from a word for battle or warrior. If you want the meaning to stay private, these are the ones to look at."),
 ("Odin, the chief Norse god, carries warrior associations, and Marcus means warlike in Latin.", "Odin is the Norse god of war and wisdom, and Marcus means dedicated to Mars, the Roman god of war."),
 ("Zelda is a German name meaning gray fighting maid.", "Zelda is a short form of Griselda, which means gray battle."),
 ("For something modern, Sloane from Irish means warrior and raider.", "For something modern, Sloane comes from an Irish surname meaning raider."),
]
