ROWS = {
 "Ethan": (None, None, None, "Strong, firm, enduring"),
 "Andrew": ("Oz", None, "Hebrew", "Strength"),
 "Gabriel": (None, None, None, "God is my strength"),
 "Liam": (None, None, None, "Short form of William, 'resolute protector'"),
 "Griffin": (None, None, None, "From Gruffudd, 'strong lord'"),
 "Arsenio": (None, None, None, "Virile, strong"),
 "Angus": (None, None, None, "One strength"),
 "Barrett": (None, None, "English", "From a surname, possibly 'bear strength'"),
 "Ezekiel": (None, None, None, "God strengthens"),
 "Kenzo": (None, None, None, "Often written with 健, 'strong, healthy'"),
 "Oswald": (None, None, None, "Divine power"),
 "Maynard": (None, None, "Germanic", "Strong and brave"),
 "Takeshi": (None, None, None, "Often written 武, 'warrior', or 健, 'strong'"),
 "Anders": ("Qawi", None, "Arabic", "Strong"),
 "Warrick": ("Fergus", None, "Scottish / Irish", "Man of vigor"),
 "Nero": (None, None, "Sabine, via Latin", "Strong, vigorous"),
 "Brian": ("Eyal", None, "Hebrew", "Strength"),
 "Chasin": ("Boaz", None, "Hebrew", "Traditionally explained as 'in him is strength'"),
 "Godric": (None, None, None, "Power of God"),
 "Valentino": (None, None, None, "Strong, healthy"),
 "Matilda": (None, None, "Germanic", "Strength in battle"),
 "Valentina": (None, None, None, "Strong, healthy"),
 "Audrey": (None, None, None, "Noble strength"),
 "Bridget": (None, None, None, "Exalted one; often glossed as 'strength'"),
 "Gabriella": (None, None, None, "Feminine form of Gabriel, 'God is my strength'"),
 "Mildred": (None, None, None, "Gentle strength"),
 "Adira": (None, None, None, "Strong, mighty"),
 "Valerie": (None, None, None, "Strong, healthy"),
 "Briana": ("Aziza", None, "Arabic", "Powerful; also 'beloved'"),
 "Karla": ("Imara", None, "Swahili", "Firm, strong"),
 "Philomena": (None, None, None, "Loved + strength; often given as 'lover of strength'"),
 "Millicent": (None, None, "Germanic", "Work + strength"),
 "Trudy": (None, None, "Germanic", "Short form of Gertrude, 'spear of strength'"),
 "Isa": (None, None, "Germanic", "From a word meaning 'ice' or 'iron'"),
 "Gertrude": (None, None, "Germanic", "Spear of strength"),
 "Bree": ("Shakti", None, "Sanskrit", "Power, energy"),
 "Valencia": (None, None, None, "Strength, valor"),
 "Keren": (None, None, None, "Horn, a symbol of strength; also 'ray of light'"),
 "Aloisia": ("Magnhild", None, "Norse", "Mighty in battle"),
 "Bedelia": ("Maude", None, "English", "Medieval form of Matilda, 'strength in battle'"),
 "Casey": ("Jian", None, "Chinese", "'Strong, healthy' when written 健"),
 "Drew": ("Chikara", "Boy", "Japanese", "'Strength' when written 力"),
 "Emery": (None, None, "Germanic", "From a name ending in ric, 'power'"),
 "Kali": ("Amandla", "Girl", "Zulu / Xhosa", "Power, strength"),
 "Aiden": ("Bala", None, "Sanskrit", "Strength"),
 "Riley": ("Magni", "Boy", "Norse", "Mighty, strong; the son of Thor"),
 "Reese": ("Uziel", "Boy", "Hebrew", "God is my strength"),
 "Phoenix": ("Ikaika", "Boy", "Hawaiian", "Strong"),
 "Sloane": ("Stark", None, "German / English", "Strong"),
 "Everett": ("Hezekiah", "Boy", "Hebrew", "God strengthens"),
}
PROSE = [
 ("> 💡 **Tip: Trending Picks** — Valentina, Kenzo, Emery, and Phoenix are surging on baby name charts in 2026. These four names blend modern appeal with deep, strength-based roots, making them standout choices for parents who want something both current and meaningful.",
  "> 💡 **Tip: One Root, Many Names** — Valentina, Valentino, Valerie, and Valencia all come from the Latin verb valere, 'to be strong'. Gabriel, Gabriella, Ezekiel, Hezekiah, and Uziel all combine strength with the Hebrew word for God."),
 ("Whether you prefer a bold, recognizable classic like Andrew or a rare gem like Valentina", "Whether you prefer a familiar classic like Ethan or Gabriel, or something rarer like Adira or Ikaika"),
 ("and [the name Ethan](/blog/name-elijah/)", "and [the name Elijah](/blog/name-elijah/)"),
 ("Yes, several unisex names carry meanings of strength. Emery, meaning brave and powerful from German origins, works beautifully for any gender. Other options include Phoenix, Casey, and Riley, all of which have strength or courage woven into their meanings.",
  "Yes. Bala means strength in Sanskrit, Jian can mean strong and healthy in Chinese, and Stark comes from the German word for strong. Emery comes from a Germanic name that ends in a word meaning power."),
 ("Absolutely. Kenzo comes from Japanese and means strong and healthy. Kali has Sanskrit roots meaning fierce strength. Takeshi is another Japanese name meaning fierce warrior. Many African, Arabic, and Asian languages also offer beautiful names rooted in power and resilience.",
  "Absolutely. Kenzo is a Japanese name often written with a character meaning strong and healthy. Shakti means power in Sanskrit, Imara means strong in Swahili, Qawi means strong in Arabic, and Ikaika means strong in Hawaiian."),
 ("For girls, Matilda and Valentina have risen sharply in recent years. ", "For girls, Matilda and Valentina are both well established. "),
]
