ROWS = {
 "Henry": (None, None, "Germanic", "Home ruler"),
 "William": (None, None, "Germanic", "Resolute protector; a name of English kings since 1066"),
 "Arthur": (None, None, None, "Meaning uncertain, possibly 'bear'; the legendary king of Britain"),
 "Charles": (None, None, "Germanic", "Free man; a name of kings across Europe"),
 "Frederick": (None, None, "Germanic", "Peaceful ruler"),
 "Rex": (None, None, None, "King"),
 "Leroy": (None, None, None, "The king"),
 "Basil": (None, None, None, "Kingly"),
 "Alaric": (None, None, "Gothic", "Ruler of all"),
 "Brendan": (None, None, None, "Prince"),
 "Cyrus": (None, None, None, "Meaning uncertain; the founder of the Persian Empire"),
 "Edmund": (None, None, None, "Rich protector; the name of two English kings"),
 "Leopold": (None, None, "Germanic", "Bold people; a name of Belgian kings and Austrian emperors"),
 "Malik": (None, None, None, "King"),
 "Patrick": (None, None, None, "Nobleman, patrician"),
 "Rory": (None, None, None, "Red king"),
 "Elizabeth": (None, None, None, "My God is an oath; the name of two British queens"),
 "Victoria": (None, None, None, "Victory; the name of Britain's Queen Victoria"),
 "Charlotte": (None, None, None, "Feminine form of Charles, 'free man'; a name of queens and princesses"),
 "Diana": (None, None, None, "Divine; the name of Diana, Princess of Wales"),
 "Eleanor": (None, None, None, "Meaning uncertain; Eleanor of Aquitaine was queen of France and then England"),
 "Amira": (None, None, None, "Princess, commander"),
 "Anastasia": (None, None, None, "Resurrection; a name of Russian grand duchesses"),
 "Rani": (None, None, None, "Queen"),
 "Adelaide": (None, None, "Germanic", "Noble kind"),
 "Guinevere": (None, None, None, "Fair and smooth; King Arthur's queen"),
 "Theodora": (None, None, None, "Gift of God; the name of a Byzantine empress"),
 "Zara": (None, None, None, "Possibly from Arabic zahrah, 'blossom'; used in the British royal family"),
 "Empress": (None, None, None, "A female sovereign"),
 "Reina": (None, None, None, "Queen"),
 "Royal": (None, None, None, "Of the king"),
 "Reagan": (None, None, None, "From an Irish surname, possibly 'little king'"),
 "Aubrey": (None, None, "Germanic, via French", "Elf ruler"),
 "Reign": (None, None, None, "To rule"),
 "Noble": (None, None, None, "Noble"),
 "Kingsley": (None, None, None, "King's meadow"),
 "Adair": ("Ryan", None, "Irish", "Little king"),
 "Sterling": ("Kingston", None, "English", "King's town"),
 "Emery": (None, None, "Germanic", "From a name ending in ric, 'ruler, power'"),
 "Tierney": (None, None, None, "From an Irish surname meaning 'lord'"),
}
PROSE = [
 ("> 💡 **Tip: Trending Picks** — Charlotte, Reign, Zara, and Alaric are the royal names making the biggest impact in 2026. Charlotte remains a perennial favorite, while Reign and Alaric offer bolder, more distinctive options for parents seeking something less traditional.",
  "> 💡 **Tip: Two Kinds of Royal Names** — Rex, Malik, Rani, and Reina literally mean king or queen. Henry, Elizabeth, Charlotte, and William mean something else entirely and are royal because kings and queens have carried them for centuries."),
 ("Zara was popularized by a British princess and has a modern, energetic feel. Alaric, meaning noble ruler, has an ancient meaning but a fresh, modern sound.",
  "Zara is used in the British royal family and has a modern, energetic feel. Alaric, meaning ruler of all, is an ancient Gothic name with a fresh sound."),
]
