ROWS = {
 "Dylan": (None, None, None, "Great tide"),
 "Kai": (None, None, None, "Sea"),
 "Morgan": (None, None, None, "Possibly 'sea chief' or 'sea circle'"),
 "Irving": (None, None, None, "Green water, fresh water"),
 "Caspian": (None, None, None, "Of the Caspian Sea"),
 "Marlow": (None, None, None, "Land left by a drained lake"),
 "Hurley": (None, None, None, "From an Irish surname, possibly 'sea tide'"),
 "Neptune": (None, None, None, "The Roman god of the sea"),
 "Murdoch": (None, None, None, "Sea warrior, mariner"),
 "Calder": (None, None, "Scottish / English", "Rough or rocky water"),
 "Brooks": (None, None, None, "Of the brook"),
 "Adrian": (None, None, None, "From Hadria, the town that gave the Adriatic Sea its name"),
 "Murphy": (None, None, None, "Sea warrior"),
 "Marina": (None, None, None, "Of the sea"),
 "Cordelia": (None, None, None, "Uncertain; sometimes explained as 'daughter of the sea'"),
 "Nerissa": (None, None, None, "From the Nereids, the sea nymphs"),
 "Maren": (None, None, "Danish", "Danish form of Marina, 'of the sea'"),
 "Moana": (None, None, "Maori / Hawaiian", "Ocean"),
 "Isla": (None, None, None, "From Islay, a Scottish island"),
 "Tallulah": (None, None, None, "Often given as 'leaping water'; from a place name in Georgia"),
 "Ondine": (None, None, None, "From Latin unda, 'wave'"),
 "Naia": (None, None, "Greek / Basque", "From the naiads, water nymphs; in Basque, 'wave'"),
 "Sereia": (None, None, None, "Mermaid"),
 "Coral": (None, None, None, "Coral"),
 "Maris": (None, None, None, "Of the sea"),
 "Ocean": (None, None, None, "Ocean"),
 "River": (None, None, None, "River"),
 "Lake": (None, None, None, "Lake"),
 "Bay": (None, None, None, "An inlet of the sea"),
 "Haven": (None, None, None, "Harbor, safe place"),
 "Marlowe": (None, None, None, "Land left by a drained lake"),
 "Reed": ("Kaito", "Boy", "Japanese", "Often written 海斗 or 海翔, beginning with 'sea'"),
 "Shiloh": ("Umi", None, "Japanese", "'Sea' when written 海"),
 "Beckett": (None, None, None, "From an English surname, possibly 'little brook'"),
 "Delta": (None, None, None, "The mouth of a river"),
}
PROSE = []
