ROWS = {
 "Orion": (None, None, None, "Meaning uncertain; the hunter constellation"),
 "Sirius": (None, None, None, "Glowing, scorching; the brightest star in the night sky"),
 "Aster": (None, None, None, "Star"),
 "Leo": (None, None, None, "Lion; the constellation Leo"),
 "Castor": (None, None, None, "One of the twin stars of Gemini; the word also means 'beaver'"),
 "Atlas": (None, None, None, "The Titan who held up the sky"),
 "Sterling": (None, None, None, "Possibly 'little star'; from the name of an old English silver coin"),
 "Altair": (None, None, None, "The flyer; the brightest star in Aquila"),
 "Draco": (None, None, None, "Dragon; the constellation Draco"),
 "Perseus": (None, None, None, "A hero of Greek myth and a constellation; the meaning is uncertain"),
 "Rigel": (None, None, None, "Foot; a bright star in Orion"),
 "Nash": (None, None, "Arabic / English", "A traditional name for a star in Sagittarius, from Arabic for 'arrowhead'; also an English surname"),
 "Pollux": (None, None, None, "One of the twin stars of Gemini; from Greek for 'very sweet'"),
 "Stella": (None, None, None, "Star"),
 "Estelle": (None, None, None, "Star"),
 "Celeste": (None, None, None, "Heavenly"),
 "Lyra": (None, None, None, "Lyre; the constellation Lyra"),
 "Nova": (None, None, None, "New; a star that suddenly brightens"),
 "Astra": (None, None, None, "Of the stars"),
 "Seren": (None, None, None, "Star"),
 "Cassiopeia": (None, None, None, "A queen in Greek myth and a constellation"),
 "Vega": (None, None, None, "From Arabic for 'swooping eagle'; the brightest star in Lyra"),
 "Danica": (None, None, None, "Morning star"),
 "Esther": (None, None, None, "Probably 'star'"),
 "Sidra": ("Citlali", None, "Nahuatl", "Star"),
 "Arista": ("Hoshi", None, "Japanese", "'Star' when written 星"),
 "Star": (None, None, None, "Star"),
 "Phoenix": (None, None, None, "The mythical bird; also a constellation in the southern sky"),
 "Skyler": ("Tara", "Girl", "Sanskrit", "Star"),
 "North": (None, None, None, "North; the North Star has guided travelers for centuries"),
 "Astro": (None, None, None, "Star"),
 "Lumi": ("Najm", None, "Arabic", "Star"),
 "Comet": (None, None, "Greek, via English", "From Greek for 'long-haired star'"),
 "Zenith": (None, None, None, "The highest point in the sky"),
 "Vesper": (None, None, None, "Evening; the evening star"),
}
PROSE = [
 ("> 💡 **Tip: Trending Picks** — Nova, Orion, Lyra, and Stella are the celestial names dominating baby name searches in 2026. These names combine cosmic grandeur with everyday wearability, making them favorites among parents who want something both extraordinary and practical.",
  "> 💡 **Tip: Star or Constellation?** — Stella, Seren, Tara, and Citlali are simply the word for star in Latin, Welsh, Sanskrit, and Nahuatl. Orion, Lyra, and Leo are constellations, and Sirius, Vega, and Rigel are individual stars you can point to in the night sky."),
 ("Nova, meaning a star that suddenly becomes brighter, has been one of the fastest-rising girl names in recent years.", "Nova is the Latin word for new, and in astronomy it means a star that suddenly becomes brighter."),
 ("Orion is a Greek name meaning rising in the sky and refers to one of the most recognizable constellations.", "Orion is the name of one of the most recognizable constellations, although the meaning of the name itself is uncertain."),
]
