ROWS = {
 "Solomon": (None, None, None, "Peace"),
 "Frederick": (None, None, "Germanic", "Peaceful ruler"),
 "Oliver": (None, None, None, "Associated with the olive tree, a symbol of peace"),
 "Pax": (None, None, None, "Peace"),
 "Geoffrey": (None, None, "Germanic", "A Germanic name ending in frid, 'peace'"),
 "Stellan": (None, None, None, "Possibly 'calm'"),
 "Absalom": (None, None, None, "Father of peace"),
 "Humphrey": (None, None, "Germanic", "Peaceful warrior"),
 "Miroslav": (None, None, None, "Peace and glory"),
 "Kazuki": (None, None, None, "When written 和希, 'harmony' + 'hope'"),
 "Axel": (None, None, None, "Scandinavian form of Absalom, 'father of peace'"),
 "Godfrey": (None, None, "Germanic", "Peace of God"),
 "Paxton": ("Wilfred", None, "English", "Desiring peace"),
 "Manfred": (None, None, "Germanic", "Man of peace"),
 "Irene": (None, None, None, "Peace"),
 "Serena": (None, None, None, "Serene, calm"),
 "Paloma": (None, None, None, "Dove, a symbol of peace"),
 "Winifred": (None, None, None, "Blessed peace"),
 "Frida": (None, None, "Germanic", "Peace"),
 "Olive": (None, None, None, "The olive tree, a symbol of peace"),
 "Salome": (None, None, None, "From shalom, 'peace'"),
 "Shanti": (None, None, None, "Peace"),
 "Mira": (None, None, None, "From mir, 'peace, world'"),
 "Galena": (None, None, None, "Calm"),
 "Concordia": (None, None, None, "Harmony"),
 "Tullia": ("Salma", None, "Arabic", "Safe, peaceful"),
 "Shiloh": (None, None, None, "Uncertain; often given as 'tranquil'"),
 "Salem": (None, None, "Hebrew / Arabic", "Complete, peaceful; safe"),
 "Paz": (None, None, "Spanish", "Peace"),
 "Ren": ("An", None, "Chinese", "'Peace' when written 安"),
 "Noah": (None, None, None, "Rest, comfort"),
 "Haven": ("Dove", None, "English", "The dove, a symbol of peace"),
 "Harmony": (None, None, None, "Harmony"),
 "Seren": ("Amani", None, "Swahili", "Peace"),
 "Lulani": ("Shalom", None, "Hebrew", "Peace"),
}
PROSE = []
