ROWS = {
 "Hugo": (None, None, "Germanic", "Mind, spirit"),
 "Alden": ("Eldred", None, "English", "Old counsel"),
 "Conall": ("Senan", None, "Irish", "Little wise one"),
 "Raymond": (None, None, "Germanic", "Wise protector"),
 "Alfred": (None, None, None, "Elf counsel"),
 "Hakim": (None, None, None, "Wise"),
 "Cato": (None, None, None, "Wise, shrewd"),
 "Aldric": ("Ronald", None, "Norse, via Scottish", "Ruler's counselor"),
 "Nestor": (None, None, None, "Homecoming; the wise old king of the Iliad"),
 "Solon": (None, None, None, "The Athenian lawgiver, one of the Seven Sages of Greece"),
 "Vivek": (None, None, None, "Wisdom, discernment"),
 "Kendry": ("Arif", None, "Arabic", "Learned, knowing"),
 "Seneca": (None, None, None, "From a Roman family name meaning 'old'; the Stoic philosopher"),
 "Raghnall": (None, None, "Irish, from Norse", "Ruler's counsel"),
 "Shanahan": (None, None, None, "From sean, 'old, wise'"),
 "Sophia": (None, None, None, "Wisdom"),
 "Phoebe": ("Medha", None, "Sanskrit", "Intelligence, wisdom"),
 "Athena": (None, None, None, "The Greek goddess of wisdom"),
 "Prudence": (None, None, None, "Good judgment"),
 "Minerva": (None, None, None, "The Roman goddess of wisdom"),
 "Ramona": (None, None, None, "Feminine form of Raymond, 'wise protector'"),
 "Cassandra": ("Sophronia", None, "Greek", "Sensible, self-controlled"),
 "Monique": (None, None, None, "French form of Monica; linked to Latin monere, 'to advise'"),
 "Alberta": ("Tomoko", None, "Japanese", "When written 智子, 'wise child'"),
 "Dara": (None, None, None, "In Hebrew, often given as 'pearl of wisdom'; in Irish, 'oak'"),
 "Mika": ("Chie", None, "Japanese", "When written 智恵, 'wisdom' + 'blessing'"),
 "Sonia": (None, None, "Russian", "Pet form of Sophia, 'wisdom'"),
 "Veda": (None, None, None, "Knowledge"),
 "Alvina": ("Hikma", None, "Arabic", "Wisdom"),
 "Bernice": ("Zofia", None, "Polish", "Polish form of Sophia, 'wisdom'"),
 "Sage": (None, None, None, "Wise; also the herb"),
 "Quinn": (None, None, None, "From Conn, 'chief' or 'intelligence'"),
 "Bodhi": (None, None, None, "Awakening, enlightenment"),
 "Raven": (None, None, None, "The raven, a bird of wisdom in Norse myth"),
 "Shannon": (None, None, None, "From the River Shannon, possibly 'old' or 'wise one'"),
 "Kieran": ("Akira", None, "Japanese", "When written 明, 'bright, intelligent'"),
 "Ellis": ("Zhi", None, "Chinese", "'Wisdom' when written 智"),
 "Rowan": ("Gyan", "Boy", "Sanskrit", "Knowledge"),
 "Kenzie": ("Hui", None, "Chinese", "'Wise' when written 慧"),
 "Reese": ("Minh", None, "Vietnamese", "Bright, intelligent"),
}
PROSE = [
 ("> 💡 **Tip: Trending Picks** — Sophia, Bodhi, Sage, and Athena continue to dominate wisdom-themed name searches in 2026. Parents love these names because they sound contemporary while carrying centuries of meaningful heritage.",
  "> 💡 **Tip: The Sophia Family** — Sophia, Sonia, and Zofia are all the same Greek name, meaning wisdom. Raymond and Ramona are a matching pair too: both mean wise protector."),
 ("For boys, Hugo and Bodhi are among the most popular wisdom-themed names. Sage has also risen dramatically as a gender-neutral wisdom name.", "For boys, Hugo means mind or spirit and Alfred means elf counsel. Sage is the English word for a wise person and works for any gender."),
 ("Kendry is a Malagasy name meaning wise man that offers a rare and distinctive sound.", "Vivek means wisdom and discernment in Sanskrit, and Hikma is the Arabic word for wisdom."),
 ("Hugo means mind and intellect in German.", "Hugo comes from a Germanic word meaning mind or spirit."),
 ("Cato, from Latin, means all-knowing and wise.", "Cato, from Latin, means wise or shrewd."),
 ("Sophia is the most popular name meaning wisdom worldwide and has held top positions on baby name charts across multiple countries for over a decade.", "Sophia is the best-known name meaning wisdom and has been near the top of baby name charts in many countries."),
]
