ROWS = {
 "Richard": (None, None, "Germanic", "Brave ruler"),
 "Leonard": (None, None, "Germanic", "Brave as a lion"),
 "Bernard": (None, None, "Germanic", "Brave as a bear"),
 "Everett": (None, None, "English, from Germanic", "Brave as a wild boar"),
 "Harvey": (None, None, "Breton, via French", "Battle worthy"),
 "Conrad": (None, None, "Germanic", "Bold counsel"),
 "Willard": (None, None, "Germanic", "Resolute and brave"),
 "Reynard": (None, None, "Germanic", "Strong, brave counsel"),
 "Howard": (None, None, "English", "Uncertain; possibly 'brave heart' or 'high guardian'"),
 "Hardy": (None, None, "Germanic", "Bold, brave"),
 "Koa": (None, None, None, "Brave, bold; also the koa tree"),
 "Baldric": (None, None, "Germanic", "Bold ruler"),
 "Archibald": (None, None, "Germanic", "Genuine and bold"),
 "Leopold": (None, None, "Germanic", "Bold people"),
 "Balder": (None, None, None, "Possibly 'brave' or 'lord'; the Norse god of light"),
 "Wyatt": (None, None, None, "Brave in war"),
 "Cedric": ("Andrew", None, "Greek", "Manly, brave"),
 "Dustin": ("Gerard", None, "Germanic", "Brave with the spear"),
 "Valerie": (None, None, None, "Strong, vigorous; from the Latin root of 'valor'"),
 "Andrea": (None, None, None, "Feminine form of Andrew, 'manly, brave'"),
 "Bernadette": (None, None, None, "Feminine form of Bernard, 'brave as a bear'"),
 "Matilda": (None, None, "Germanic", "Mighty in battle"),
 "Trudy": (None, None, "Germanic", "Short form of Gertrude, 'strength of the spear'"),
 "Maia": ("Veera", None, "Sanskrit", "Brave, heroic"),
 "Brielle": ("Valencia", None, "Latin, via Spanish", "Strength, valor"),
 "Valentina": (None, None, None, "Strong, vigorous"),
 "Leona": (None, None, None, "Lioness, a symbol of courage"),
 "Moxie": (None, None, "American English", "Nerve, courage, determination"),
 "Geraldine": ("Richelle", None, "French", "Feminine form of Richard, 'brave ruler'"),
 "Bria": ("Abhaya", None, "Sanskrit", "Fearless"),
 "Fernanda": (None, None, "Germanic, via Spanish", "Bold voyager"),
 "Millicent": ("Basila", None, "Arabic", "Brave"),
 "Sharya": ("Bernardine", None, "French", "Feminine form of Bernard, 'brave as a bear'"),
 "Tyra": ("Andrina", None, "Scottish", "Feminine form of Andrew, 'brave'"),
 "Kiera": ("Leonarda", None, "Italian", "Feminine form of Leonard, 'brave as a lion'"),
 "Casey": ("Jasiri", None, "Swahili", "Brave, bold"),
 "Riley": (None, None, "Irish / English", "Often given as 'valiant' from Irish; also English 'rye clearing'"),
 "Emery": ("Courage", None, "English", "Bravery"),
 "Valor": (None, None, None, "Bravery, courage"),
 "Phoenix": ("Yong", None, "Chinese / Korean", "'Brave' when written 勇"),
 "Bailey": ("Kekoa", "Boy", "Hawaiian", "The brave one, the warrior"),
 "Drew": (None, None, None, "Short form of Andrew, 'manly, brave'"),
 "Harley": ("Shaurya", None, "Sanskrit", "Bravery, valor"),
 "Jesse": ("Andy", None, "English", "Short form of Andrew or Andrea, 'brave'"),
 "Tierney": ("Ari", None, "Hebrew", "Lion, a symbol of courage"),
}
PROSE = [
 ("> 💡 **Tip: Trending Picks** — Koa, Valor, Brielle, and Wyatt are making waves on 2026 baby name charts. These names feel fresh and bold while carrying deep roots in the language of courage, perfect for parents who want a name that stands out.",
  "> 💡 **Tip: Modern-Sounding Picks** — Koa, Valor, and Wyatt feel fresh while carrying deep roots in the language of courage. If you want the meaning without the boldness, Andrew, Drew, and Andrea all come from the Greek word for brave."),
 ("Valor James, Brielle Rose, or Koa Alexander", "Valor James, Valencia Rose, or Koa Alexander"),
 ("Valentina, from Latin, means brave, strong, and vigorous. Matilda is a German name meaning mighty in battle. Leona, meaning lioness, conveys natural bravery. For something more modern, Brielle and Moxie both carry bold, courageous energy.",
  "Andrea is the feminine form of Andrew, from the Greek word for brave. Bernadette means brave as a bear, and Veera comes from the Sanskrit word for brave or heroic. Valentina and Valerie share the Latin root of the word valor, and Matilda means mighty in battle."),
 ("Valor is a direct Latin word-name meaning bravery and courage that works for any gender. Emery, meaning brave and powerful, is another popular unisex option. Casey from Irish means brave and vigilant, and Riley means courageous and valiant.",
  "Valor is a word-name meaning bravery and courage that works for any gender. Drew is a short form of Andrew, meaning brave. Jasiri means brave in Swahili, Shaurya means bravery in Sanskrit, and Riley is often given the meaning valiant."),
 ("Several boy names carry the meaning of brave. Richard is a classic German name meaning brave ruler. Leonard means brave lion.", "Several boy names carry the meaning of brave. Richard is a classic Germanic name meaning brave ruler. Leonard means brave as a lion."),
]
