ROWS = {
 "Dylan": (None, None, None, "Great tide"),
 "Adrian": (None, None, None, "From Hadria, the town that gave the Adriatic Sea its name"),
 "Morgan": (None, None, None, "Possibly 'sea chief' or 'sea circle'"),
 "Nolan": (None, None, None, "From an Irish surname meaning 'noble, famous'"),
 "Ira": (None, None, None, "Watchful"),
 "Tristan": (None, None, None, "From the Celtic name Drustan; linked by legend to French triste, 'sad'"),
 "Dorian": (None, None, None, "Of the Dorians, an ancient Greek people"),
 "Calder": (None, None, None, "Rough or rocky water"),
 "Arun": (None, None, None, "Dawn"),
 "Caleb": (None, None, None, "Meaning uncertain; often given as 'whole-hearted'"),
 "Dillon": (None, None, "Welsh / Irish", "A form of Dylan; also an Irish surname"),
 "Everest": (None, None, None, "From an English surname; the name of the world's highest mountain"),
 "Gabriel": (None, None, None, "God is my strength"),
 "Kai": (None, None, None, "Sea"),
 "Lir": (None, None, None, "The sea; the Irish god of the sea"),
 "Milo": (None, None, None, "Meaning uncertain; possibly 'gracious'"),
 "Neptune": (None, None, None, "The Roman god of the sea"),
 "Shiloh": (None, None, None, "Uncertain; often given as 'tranquil'"),
 "Wilder": (None, None, None, "Wild, untamed"),
 "Aldous": (None, None, None, "Old"),
 "Corin": (None, None, None, "From Quirinus, possibly 'spear'"),
 "Cordelia": (None, None, None, "Uncertain; sometimes explained as 'daughter of the sea'"),
 "Melody": (None, None, None, "Song"),
 "Ariel": (None, None, None, "Lion of God; also the spirit in Shakespeare's The Tempest"),
 "Serena": (None, None, None, "Serene, calm"),
 "Pearl": (None, None, None, "Pearl"),
 "Calypso": (None, None, None, "She who conceals; a sea nymph in the Odyssey"),
 "Iris": (None, None, None, "Rainbow; the messenger goddess"),
 "Leilani": (None, None, None, "Heavenly flowers"),
 "Ondine": (None, None, None, "From Latin unda, 'wave'"),
 "Coral": (None, None, None, "Coral"),
 "Nerissa": (None, None, None, "From the Nereids, the sea nymphs"),
 "Amara": (None, None, None, "In Igbo, 'grace'; in Sanskrit, 'immortal'"),
 "Beatrix": (None, None, None, "She who brings happiness; originally Viatrix, 'voyager'"),
 "Esme": (None, None, "Old French", "Esteemed, loved"),
 "Fiona": (None, None, "Scottish", "White, fair"),
 "Giselle": (None, None, None, "Pledge"),
 "Isla": (None, None, None, "From Islay, a Scottish island"),
 "Larissa": (None, None, None, "A city in Greece, possibly 'citadel'"),
 "Mirabel": (None, None, None, "Wonderful"),
 "Selene": (None, None, None, "Moon"),
}
PROSE = []
