ROWS = {
 "Quinn": (None, None, None, "From Conn, 'chief' or 'intelligence'"),
 "Atlas": (None, None, None, "The Titan who held up the sky"),
 "Everett": (None, None, None, "Brave as a wild boar"),
 "Wilder": (None, None, None, "Wild, untamed"),
 "Cato": (None, None, None, "Wise, shrewd"),
 "Blaze": (None, None, None, "Flame"),
 "Colton": (None, None, None, "Coal town"),
 "Waylan": (None, None, None, "Land by the road"),
 "Hugo": (None, None, None, "Mind, spirit"),
 "Apollo": (None, None, None, "The Greek god of light, music, and archery"),
 "Finnegan": (None, None, None, "From an Irish surname meaning 'fair'"),
 "Bodhi": (None, None, None, "Awakening, enlightenment"),
 "Leif": (None, None, None, "Heir, descendant"),
 "Jasper": (None, None, None, "Treasurer"),
 "Rowan": (None, None, None, "Little red-haired one; also the rowan tree"),
 "Caleb": (None, None, None, "Meaning uncertain; often given as 'whole-hearted'"),
 "Sterling": (None, None, None, "Of high quality; from the name of an old English silver coin"),
 "Dashiell": (None, None, None, "From a French surname; meaning uncertain"),
 "Altair": (None, None, None, "The flyer; the brightest star in Aquila"),
 "Idris": (None, None, None, "In Welsh, 'ardent lord'; in Arabic, the name of a prophet"),
 "Artemis": (None, None, None, "The Greek goddess of the hunt and the moon"),
 "Sage": (None, None, None, "Wise; also the herb"),
 "Wren": (None, None, None, "A small songbird"),
 "Vera": (None, None, None, "Faith; also Latin for 'true'"),
 "Athena": (None, None, None, "The Greek goddess of wisdom"),
 "Journey": (None, None, None, "A journey"),
 "Clementine": (None, None, None, "Merciful"),
 "Diana": (None, None, None, "Divine; the Roman goddess of the hunt"),
 "Faye": (None, None, None, "Fairy"),
 "Haven": (None, None, None, "Harbor, safe place"),
 "Thalia": (None, None, None, "To blossom; the muse of comedy"),
 "Scout": (None, None, None, "To explore, to gather information"),
 "Valentina": (None, None, None, "Strong, vigorous"),
 "Kira": (None, None, None, "Russian feminine form of Cyrus"),
 "Adelaide": (None, None, None, "Noble kind"),
 "Brielle": (None, None, None, "Short form of Gabrielle, 'God is my strength'"),
 "Zara": (None, None, "Arabic", "Possibly from Arabic zahrah, 'blossom'"),
 "Ember": (None, None, None, "A glowing coal"),
 "Nova": (None, None, None, "New"),
 "Juniper": (None, None, None, "The juniper, an evergreen shrub"),
}
PROSE = []
