ROWS = {
 "Anders": (None, None, None, "Scandinavian form of Andrew, 'manly, brave'"),
 "Finn": (None, None, None, "From Old Norse Finnr, 'a Sámi person, wanderer'"),
 "Gunnar": (None, None, None, "Battle warrior"),
 "Knut": (None, None, None, "Knot"),
 "Lars": (None, None, None, "Scandinavian form of Lawrence, 'from Laurentum'"),
 "Leif": (None, None, None, "Heir, descendant"),
 "Nils": (None, None, None, "Scandinavian form of Nicholas, 'victory of the people'"),
 "Odin": (None, None, None, "Frenzy, inspiration; chief of the Norse gods"),
 "Ragnar": (None, None, None, "Counsel + warrior"),
 "Soren": (None, None, None, "Danish form of Severinus, 'stern'"),
 "Astrid": (None, None, None, "Divinely beautiful"),
 "Birgit": (None, None, None, "Scandinavian form of Bridget, 'exalted one'"),
 "Dagny": (None, None, None, "New day"),
 "Elsa": (None, None, None, "Short form of Elisabeth, 'my God is an oath'"),
 "Freya": (None, None, None, "Lady; the Norse goddess of love"),
 "Greta": (None, None, None, "Short form of Margareta, 'pearl'"),
 "Hilda": (None, None, None, "Battle"),
 "Ingrid": (None, None, None, "Ing is beautiful; Ing was a Norse god"),
 "Karin": (None, None, None, "Swedish form of Katherine"),
 "Linnea": (None, None, None, "The twinflower, named for botanist Carl Linnaeus"),
 "Liv": (None, None, None, "Life; in Old Norse, 'shelter'"),
 "Maja": (None, None, None, "Scandinavian form of Maia; also a pet form of Maria"),
 "Solveig": (None, None, None, "Meaning uncertain; possibly 'sun' or 'house' + 'strength'"),
 "Thora": (None, None, None, "Feminine form of Thor, 'thunder'"),
 "Bo": (None, None, None, "To live, to dwell"),
 "Edda": (None, None, None, "Possibly 'great-grandmother'; the name of the Old Norse poetry collections"),
 "Kai": (None, None, None, "Meaning uncertain in Scandinavia; in Hawaiian, 'sea'"),
 "Kim": (None, None, None, "Short form of Joakim"),
 "Loke": (None, None, None, "The trickster god of Norse myth"),
 "Ronja": (None, None, None, "Coined by Astrid Lindgren for her novel Ronia, the Robber's Daughter"),
 "Saga": (None, None, None, "Story; also a Norse goddess"),
 "Sindri": (None, None, None, "Sparkling; a dwarf in Norse myth"),
 "Tove": (None, None, None, "From Old Norse Tófa, a name linked to Thor"),
}
PROSE = []
