ROWS = {
 "Phoenix": (None, None, None, "Dark red; the mythical bird reborn from fire"),
 "Griffin": (None, None, None, "From Gruffudd, 'strong lord'"),
 "Damian": (None, None, None, "To tame"),
 "Magnus": (None, None, None, "Great"),
 "Draven": (None, None, None, "From the surname of the hero of The Crow; meaning uncertain"),
 "Brennan": (None, None, None, "Descendant of Braonán, 'sorrow' or 'drop'"),
 "Alaric": (None, None, "Gothic", "Ruler of all"),
 "Orion": (None, None, None, "Meaning uncertain; the hunter constellation"),
 "Damon": (None, None, None, "To tame"),
 "Evander": (None, None, None, "Good man"),
 "Kael": (None, None, None, "From Irish caol, 'slender'"),
 "Samson": (None, None, None, "From shemesh, 'sun'"),
 "Cyrus": (None, None, None, "Meaning uncertain; the founder of the Persian Empire"),
 "Drake": (None, None, None, "Dragon; also a male duck"),
 "Ulric": (None, None, None, "Wolf ruler; or a form of Ulrich, 'prosperity and power'"),
 "Zane": (None, None, "English", "Meaning uncertain; sometimes explained as a form of John"),
 "Knox": (None, None, None, "Round hill"),
 "Raven": (None, None, None, "The raven"),
 "Lilith": (None, None, None, "Of the night; a figure of Jewish folklore"),
 "Valeria": (None, None, None, "Strong, healthy"),
 "Kendra": (None, None, None, "Feminine form of Kendrick; meaning uncertain"),
 "Tempest": (None, None, None, "Storm"),
 "Ondine": (None, None, None, "From Latin unda, 'wave'"),
 "Elektra": (None, None, None, "Amber; shining"),
 "Briar": (None, None, None, "A thorny shrub"),
 "Cordelia": (None, None, None, "Uncertain; sometimes explained as 'daughter of the sea'"),
 "Seraphina": (None, None, None, "From the seraphim, 'the burning ones'"),
 "Persephone": (None, None, None, "Meaning uncertain; the queen of the underworld in Greek myth"),
 "Enya": (None, None, None, "Anglicized form of Eithne, 'kernel'"),
 "Morgana": (None, None, None, "Feminine form of Morgan; the enchantress of Arthurian legend"),
 "Thea": (None, None, None, "Short form of Dorothea or Theodora; also Theia, the Titan goddess of light"),
 "Astrid": (None, None, None, "Divinely beautiful"),
 "Isolde": (None, None, None, "Meaning uncertain; possibly 'ice ruler'"),
 "Lorelei": (None, None, None, "A rock on the Rhine, probably 'murmuring rock'; in legend, a siren"),
 "Vesper": (None, None, None, "Evening; the evening star"),
 "Ingrid": (None, None, None, "Ing is beautiful; Ing was a Norse god"),
 "Arya": (None, None, None, "Noble"),
 "Reverie": (None, None, None, "Daydream"),
}
PROSE = []
