ROWS = {
 "Alistair": (None, None, None, "Scottish form of Alexander, 'defender of men'"),
 "Angus": (None, None, None, "One strength"),
 "Blair": (None, None, None, "Field, plain"),
 "Broderick": (None, None, None, "From a Welsh surname, 'son of Rhydderch'"),
 "Duncan": (None, None, None, "Brown warrior"),
 "Fergus": (None, None, None, "Man of vigor"),
 "Finlay": (None, None, None, "Fair warrior"),
 "Fraser": (None, None, None, "Meaning uncertain; linked by tradition to French fraise, 'strawberry'"),
 "Lennox": (None, None, None, "Place of elms"),
 "Murray": (None, None, None, "From Moray, 'settlement by the sea'"),
 "Ailsa": (None, None, None, "From Ailsa Craig, an island in the Firth of Clyde"),
 "Bonnie": (None, None, None, "Pretty"),
 "Eilidh": (None, None, None, "Scottish Gaelic form of Helen"),
 "Elspeth": (None, None, None, "Scottish form of Elizabeth, 'my God is an oath'"),
 "Kenna": (None, None, None, "Feminine form of Kenneth"),
 "Morag": (None, None, None, "Great"),
 "Morven": (None, None, None, "Big peak"),
 "Nessa": (None, None, None, "Pet form of Agnes; also linked to ness, 'headland'"),
 "Rhona": (None, None, None, "Possibly from the island of Rona, 'rough island'"),
 "Lindsay": (None, None, None, "From an English place name, possibly 'linden island'"),
 "Morgan": (None, None, None, "Possibly 'sea chief' or 'sea circle'; Welsh in origin"),
 "Rowan": (None, None, None, "Little red-haired one; also the rowan tree"),
 "Stewart": (None, None, None, "Steward"),
}
PROSE = []
