ROWS = {
 "Alejandro": (None, None, None, "Defender of men"),
 "Andrés": (None, None, None, "Manly, brave"),
 "Diego": (None, None, None, "Meaning uncertain; possibly from Santiago, 'Saint James'"),
 "Emilio": (None, None, None, "From the Roman family name Aemilius, 'rival'"),
 "Felipe": (None, None, None, "Lover of horses"),
 "Fernando": (None, None, None, "Bold voyager"),
 "Hugo": (None, None, None, "Mind, spirit"),
 "Javier": (None, None, None, "New house"),
 "Joaquin": (None, None, None, "Raised by God"),
 "Lucas": (None, None, None, "From Lucania"),
 "Marco": (None, None, None, "Dedicated to Mars"),
 "Sebastian": (None, None, None, "From Sebaste; from a Greek word meaning 'venerable'"),
 "Adriana": (None, None, None, "From Hadria"),
 "Catalina": (None, None, None, "Spanish form of Katherine"),
 "Elena": (None, None, None, "Form of Helen; probably 'torch' or 'shining light'"),
 "Emilia": (None, None, None, "Feminine form of Emilio, 'rival'"),
 "Isabel": (None, None, None, "Spanish form of Elizabeth, 'my God is an oath'"),
 "Marisol": (None, None, None, "A blend of María and Soledad; popularly understood as 'sea and sun'"),
 "Natalia": (None, None, None, "Christmas Day"),
 "Pilar": (None, None, None, "Pillar; from a title of the Virgin Mary"),
 "Valeria": (None, None, None, "Strong, healthy"),
 "Ximena": (None, None, None, "Possibly a form of Simon, 'he has heard'"),
 "Guadalupe": (None, None, None, "From a place name, possibly 'river of the wolf'"),
}
PROSE = []
