ROWS = {
 "Adam": (None, None, None, "Man; from the Hebrew word for earth"),
 "Terrence": (None, None, None, "From a Roman family name; meaning uncertain"),
 "Forrest": (None, None, None, "Of the forest"),
 "Cedric": (None, None, "English", "Coined by Sir Walter Scott for Ivanhoe; meaning uncertain"),
 "Silas": (None, None, None, "From Silvanus, 'of the forest'"),
 "Rowan": (None, None, None, "Little red-haired one; also the rowan tree"),
 "Clay": (None, None, None, "Clay, earth"),
 "Evergreen": (None, None, None, "A tree that stays green all year"),
 "Sterling": (None, None, None, "Of high quality; from the name of an old English silver coin"),
 "Leland": (None, None, None, "Fallow land"),
 "Jasper": (None, None, None, "Treasurer"),
 "Oren": (None, None, None, "Pine tree"),
 "Theodore": (None, None, None, "Gift of God"),
 "Bryce": (None, None, None, "Possibly 'speckled'"),
 "Atlas": (None, None, None, "The Titan who held up the sky"),
 "Heath": (None, None, None, "Heathland"),
 "George": (None, None, None, "Farmer"),
 "Oliver": (None, None, None, "Associated with the olive tree"),
 "Callum": (None, None, None, "Dove"),
 "Leander": (None, None, None, "Lion man"),
 "Damon": (None, None, None, "To tame"),
 "Oakley": (None, None, None, "Oak meadow"),
 "Benedict": (None, None, None, "Blessed"),
 "Gareth": (None, None, None, "Meaning uncertain; a knight of King Arthur's Round Table"),
 "Emery": (None, None, "Germanic", "From a name ending in ric, 'power'"),
 "Ivy": (None, None, None, "The ivy plant"),
 "Terra": (None, None, None, "Earth"),
 "Hazel": (None, None, None, "The hazel tree"),
 "Gemma": (None, None, None, "Gem, jewel"),
 "Dahlia": (None, None, "Swedish, via botany", "The dahlia flower, named for botanist Anders Dahl"),
 "Rosalind": (None, None, "Germanic", "'Horse' + 'tender'; later read as Latin for 'pretty rose'"),
 "Meadow": (None, None, None, "A field of grass"),
 "Fern": (None, None, None, "The fern plant"),
 "Vivienne": (None, None, None, "Alive"),
 "Laurel": (None, None, None, "The laurel tree"),
 "Petra": (None, None, None, "Rock"),
 "Eden": (None, None, None, "Delight"),
 "Briar": (None, None, None, "A thorny shrub"),
 "Florence": (None, None, None, "Flourishing"),
 "Gaia": (None, None, None, "Earth; the Greek goddess of the earth"),
 "Sage": (None, None, None, "Wise; also the herb"),
 "Willow": (None, None, None, "The willow tree"),
 "Celeste": (None, None, None, "Heavenly"),
 "Mabel": (None, None, None, "Lovable"),
 "Sienna": (None, None, None, "Reddish-brown; from the city of Siena"),
 "Daisy": (None, None, None, "Day's eye; the daisy"),
 "Magnolia": (None, None, "French, via botany", "The magnolia tree, named for botanist Pierre Magnol"),
 "Olive": (None, None, None, "The olive tree"),
 "Sylvia": (None, None, None, "Of the forest"),
 "Aurelia": (None, None, None, "Golden"),
}
PROSE = []
