ROWS = {
 "Alden": (None, None, None, "Old friend"),
 "Benedict": (None, None, None, "Blessed"),
 "Calvin": (None, None, None, "Bald"),
 "Desmond": (None, None, None, "From South Munster, a region of Ireland"),
 "Elliott": (None, None, None, "From Elias, the Greek form of Elijah, 'my God is Yahweh'"),
 "Frederick": (None, None, "Germanic", "Peaceful ruler"),
 "Graham": (None, None, None, "Gravelly homestead"),
 "Hugh": (None, None, "Germanic", "Mind, spirit"),
 "Isaac": (None, None, None, "He will laugh"),
 "Julian": (None, None, None, "From Julius; possibly 'youthful'"),
 "Kenneth": (None, None, None, "From two Gaelic names meaning 'born of fire' and 'handsome'"),
 "Lawrence": (None, None, None, "From Laurentum, a city whose name may come from 'laurel'"),
 "Maxwell": (None, None, None, "Mack's stream"),
 "Nathaniel": (None, None, None, "God has given"),
 "Owen": (None, None, None, "Possibly 'well-born' or 'youth'"),
 "Philip": (None, None, None, "Lover of horses"),
 "Reid": (None, None, None, "Red-haired"),
 "Sebastian": (None, None, None, "From Sebaste; from a Greek word meaning 'venerable'"),
 "Tobias": (None, None, None, "God is good"),
 "Virgil": (None, None, None, "From a Roman family name; the poet Virgil"),
 "Wesley": (None, None, None, "Western meadow"),
 "Xavier": (None, None, None, "New house"),
 "Cedric": (None, None, "English", "Coined by Sir Walter Scott for Ivanhoe; meaning uncertain"),
 "Alistair": (None, None, None, "Scottish form of Alexander, 'defender of men'"),
 "Adelaide": (None, None, "Germanic", "Noble kind"),
 "Beatrice": (None, None, None, "She who brings happiness"),
 "Catherine": (None, None, None, "Meaning uncertain; long associated with Greek katharos, 'pure'"),
 "Daphne": (None, None, None, "Laurel"),
 "Eleanor": (None, None, "French", "Meaning uncertain"),
 "Frances": (None, None, None, "Frenchman; later understood as 'free one'"),
 "Genevieve": (None, None, None, "Meaning uncertain; possibly 'woman of the people'"),
 "Harriet": (None, None, "English", "Feminine form of Henry, 'home ruler'"),
 "Imogen": (None, None, None, "Probably 'maiden'"),
 "Josephine": (None, None, None, "Feminine form of Joseph, 'God will add'"),
 "Katherine": (None, None, None, "Meaning uncertain; long associated with Greek katharos, 'pure'"),
 "Louisa": (None, None, "Germanic", "Feminine form of Louis, 'famous warrior'"),
 "Margaret": (None, None, None, "Pearl"),
 "Nora": (None, None, None, "Short form of Honora, 'honor', or of Eleanor"),
 "Ophelia": (None, None, None, "Help"),
 "Prudence": (None, None, None, "Good judgment"),
 "Rosalind": (None, None, "Germanic", "'Horse' + 'tender'; later read as Latin for 'pretty rose'"),
 "Sophia": (None, None, None, "Wisdom"),
 "Teresa": (None, None, None, "Meaning uncertain; possibly 'harvest' or 'summer'"),
 "Ursula": (None, None, None, "Little bear"),
 "Violet": (None, None, None, "The violet flower; purple"),
 "Willa": (None, None, "Germanic", "Feminine form of William, 'resolute protector'"),
 "Clara": (None, None, None, "Clear, bright"),
 "Edith": (None, None, None, "Rich in war"),
 "Flora": (None, None, None, "Flower; the Roman goddess of flowers and spring"),
}
PROSE = []
