ROWS = {
 "Alun": (None, None, None, "Meaning uncertain; from a Welsh river name"),
 "Aneurin": (None, None, None, "Possibly from Latin Honorius, 'man of honor'"),
 "Bedwyr": (None, None, None, "Sir Bedivere of Arthurian legend; meaning uncertain"),
 "Cadoc": (None, None, None, "Battle"),
 "Dylan": (None, None, None, "Great tide"),
 "Geraint": (None, None, None, "From Latin Gerontius, 'old man'"),
 "Gethin": (None, None, None, "Dusky, swarthy"),
 "Idris": (None, None, None, "Ardent lord"),
 "Llywelyn": (None, None, None, "Possibly 'leader'; often linked to llew, 'lion'"),
 "Owain": (None, None, None, "Possibly 'well-born' or 'youth'"),
 "Rhodri": (None, None, None, "Wheel + ruler"),
 "Angharad": (None, None, None, "Much loved"),
 "Branwen": (None, None, None, "Fair raven"),
 "Carys": (None, None, None, "Love"),
 "Cerys": (None, None, None, "Love"),
 "Dwynwen": (None, None, None, "The patron saint of Welsh lovers; the name ends in gwen, 'white, blessed'"),
 "Gwyneth": (None, None, None, "From Gwynedd, a region of Wales; or from gwyn, 'blessed'"),
 "Megan": (None, None, None, "Welsh pet form of Margaret, 'pearl'"),
 "Nerys": (None, None, None, "Lady"),
 "Rhiannon": (None, None, None, "Great queen"),
 "Tegan": (None, None, None, "From teg, 'fair, beautiful'"),
 "Morgan": (None, None, None, "Possibly 'sea chief' or 'sea circle'"),
}
PROSE = []
